import{readFileSync}from'node:fs'
import{describe,expect,it}from'vitest'
const sql=readFileSync('supabase/migrations/20260928000000_live_groups.sql','utf8')
const fix=readFileSync('supabase/migrations/20260929000000_fix_live_group_integrations.sql','utf8')
const storageFix=readFileSync('supabase/migrations/20260930000000_fix_live_group_asset_insert_policy.sql','utf8')
const memberReadFix=readFileSync('supabase/migrations/20261001000000_fix_live_group_asset_member_read.sql','utf8')
const publicGroups=readFileSync('supabase/migrations/20261003000000_public_live_groups.sql','utf8')
const publicCoverFix=readFileSync('supabase/migrations/20261004000000_fix_public_live_group_cover_read.sql','utf8')
const standaloneGroups=readFileSync('supabase/migrations/20261005000000_standalone_public_live_groups.sql','utf8')
const archivedGroups=readFileSync('supabase/migrations/20261006000000_archive_live_groups.sql','utf8')
const groupActions=readFileSync('app/admin/grupos/actions.ts','utf8')
describe('seguridad de grupos en vivo',()=>{it('separa matrícula de membresía',()=>{expect(sql).toContain('create table public.live_group_members');expect(sql).toContain('primary key (group_id, student_id)');expect(sql).toContain('active enrollment required');expect(sql).toContain('live group membership required')});it('protege todas las tablas con RLS',()=>{for(const table of ['live_groups','live_group_members','live_group_sections','live_group_items','live_group_announcements'])expect(sql).toContain(`alter table public.${table} enable row level security`)});it('mantiene assets privados y restringidos',()=>{expect(sql).toContain("'live-group-assets','live-group-assets',false");expect(sql).toContain('live_group_assets_authorized_read');expect(sql).toContain('public.is_live_group_member')});it('impone fecha, cantidad y tamaño por archivo en servidor',()=>{expect(sql).toContain("raise exception 'deadline passed'");expect(sql).toContain('jsonb_array_length(p_files)>v_max_files');expect(sql).toContain("(f->>'size_bytes')::integer>v_max_each");expect(sql).toMatch(/pdf\|doc\|docx/)});it('reutiliza actividades y revisiones',()=>{expect(sql).toContain('references public.activities');expect(sql).toContain('public.review_student_activity');expect(sql).toContain('public.submissions')})})
describe('correcciones incrementales de grupos',()=>{it('permite solo las dos rutas reales de assets',()=>{expect(fix).toContain("array_length(storage.foldername(name), 1) = 2");expect(fix).toContain("in ('covers', 'materials')");expect(fix).toContain("where g.id = (storage.foldername(name))[1]::uuid")});it('concede delivery_mode y corrige el slug de Intermedio',()=>{expect(fix).toContain('grant select (delivery_mode)');expect(fix).toContain("'python-intermedio'")})})
describe('policy final de escritura de assets',()=>{it('autoriza solo admins y rutas UUID/covers|materials sin la subconsulta cruzada',()=>{expect(storageFix).toContain("bucket_id = 'live-group-assets'");expect(storageFix).toContain('(select public.is_admin())');expect(storageFix).toContain('array_length(storage.foldername(name), 1) = 2');expect(storageFix).toContain("in ('covers', 'materials')");expect(storageFix).toContain('[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}');expect(storageFix).not.toContain('from public.live_groups')})})
describe('policy final de lectura de assets',()=>{it('permite firmar al admin o miembro mediante el helper seguro',()=>{expect(memberReadFix).toContain("bucket_id = 'live-group-assets'");expect(memberReadFix).toContain('(select public.is_admin())');expect(memberReadFix).toContain('public.is_live_group_member');expect(memberReadFix).toContain("in ('covers', 'materials')");expect(memberReadFix).not.toContain('from public.live_groups')})})
describe('grupos públicos',()=>{
  it('limita autoinscripción a grupos públicos activos',()=>{expect(publicGroups).toContain("g.access_type = 'public' and g.status = 'active'");expect(publicGroups).toContain("raise exception 'public group unavailable'");expect(publicGroups).toContain("p.role = 'student'")})
  it('crea matrícula y membresía en la misma función protegida',()=>{expect(publicGroups).toContain('security definer');expect(publicGroups).toContain('insert into public.enrollments');expect(publicGroups).toContain('insert into public.live_group_members');expect(publicGroups).toContain('grant execute on function public.join_public_live_group(uuid) to authenticated')})
  it('mantiene privados los materiales y expone sólo portadas públicas listadas',()=>{expect(publicGroups).toContain("(storage.foldername(name))[2] = 'covers'");expect(publicGroups).toContain('g.show_banner or g.show_catalog');expect(publicGroups).not.toContain("(storage.foldername(name))[2] = 'materials'")})
})

describe('archivado administrativo de grupos',()=>{
  it('añade una marca reversible sin alterar estado ni eliminar datos',()=>{expect(archivedGroups).toContain('add column archived_at timestamptz');expect(archivedGroups).not.toContain('delete from');expect(archivedGroups).not.toContain('status =')})
  it('protege archivar y restaurar en servidor y sólo actualiza archived_at',()=>{expect(groupActions).toMatch(/archiveGroup[\s\S]*?requireAdmin\(\)[\s\S]*?update\(\{archived_at:new Date\(\)\.toISOString\(\)\}\)/);expect(groupActions).toMatch(/restoreGroup[\s\S]*?requireAdmin\(\)[\s\S]*?update\(\{archived_at:null\}\)/);expect(groupActions).not.toContain("from('live_groups').delete()")})
  it('conserva la policy administrativa existente como segunda barrera',()=>{expect(sql).toContain('create policy live_groups_admin_manage');expect(sql).toContain('public.is_admin()')})
})
describe('lectura de portadas públicas',()=>{
  it('usa un helper seguro y limita la policy a covers visibles',()=>{expect(publicCoverFix).toContain('security definer');expect(publicCoverFix).toContain("g.access_type = 'public'");expect(publicCoverFix).toContain("g.status = 'active'");expect(publicCoverFix).toContain('g.show_banner or g.show_catalog');expect(publicCoverFix).toContain("(storage.foldername(name))[2] = 'covers'");expect(publicCoverFix).toContain('public.is_public_live_group_cover');expect(publicCoverFix).not.toContain("(storage.foldername(name))[2] = 'materials'")})
  it('no altera las policies privadas de admin o miembros',()=>{expect(publicCoverFix).not.toContain('live_group_assets_authorized_read');expect(publicCoverFix).not.toContain('live_group_assets_admin_')})
})
describe('grupos públicos independientes',()=>{
  it('mantiene curso obligatorio sólo en grupos privados',()=>{expect(standaloneGroups).toContain('alter table public.live_groups alter column course_id drop not null');expect(standaloneGroups).toContain("check (access_type = 'public' or course_id is not null)")})
  it('autoinscribe sin inventar matrícula cuando no hay curso',()=>{expect(standaloneGroups).toContain('if v_course is not null then');expect(standaloneGroups).toContain('insert into public.live_group_members');expect(standaloneGroups).toContain('if v_slug is null then')})
  it('autoriza actividades y entregas independientes mediante membresía',()=>{expect(standaloneGroups).toContain('alter table public.activities alter column course_id drop not null');expect(standaloneGroups).toContain('alter table public.submissions alter column course_id drop not null');expect(standaloneGroups).toContain('public.is_live_group_member(v_group)');expect(standaloneGroups).toContain("'/mi-coa/grupos/'||v_group_slug")})
  it('conserva matrícula para contenido sin grupo o con curso asociado',()=>{expect(standaloneGroups).toContain("raise exception 'active enrollment required'");expect(standaloneGroups).toContain('e.course_id = g.course_id')})
})
