import{readFileSync}from'node:fs'
import{describe,expect,it}from'vitest'
const sql=readFileSync('supabase/migrations/20260928000000_live_groups.sql','utf8')
const fix=readFileSync('supabase/migrations/20260929000000_fix_live_group_integrations.sql','utf8')
const storageFix=readFileSync('supabase/migrations/20260930000000_fix_live_group_asset_insert_policy.sql','utf8')
const memberReadFix=readFileSync('supabase/migrations/20261001000000_fix_live_group_asset_member_read.sql','utf8')
describe('seguridad de grupos en vivo',()=>{it('separa matrícula de membresía',()=>{expect(sql).toContain('create table public.live_group_members');expect(sql).toContain('primary key (group_id, student_id)');expect(sql).toContain('active enrollment required');expect(sql).toContain('live group membership required')});it('protege todas las tablas con RLS',()=>{for(const table of ['live_groups','live_group_members','live_group_sections','live_group_items','live_group_announcements'])expect(sql).toContain(`alter table public.${table} enable row level security`)});it('mantiene assets privados y restringidos',()=>{expect(sql).toContain("'live-group-assets','live-group-assets',false");expect(sql).toContain('live_group_assets_authorized_read');expect(sql).toContain('public.is_live_group_member')});it('impone fecha, cantidad y tamaño por archivo en servidor',()=>{expect(sql).toContain("raise exception 'deadline passed'");expect(sql).toContain('jsonb_array_length(p_files)>v_max_files');expect(sql).toContain("(f->>'size_bytes')::integer>v_max_each");expect(sql).toMatch(/pdf\|doc\|docx/)});it('reutiliza actividades y revisiones',()=>{expect(sql).toContain('references public.activities');expect(sql).toContain('public.review_student_activity');expect(sql).toContain('public.submissions')})})
describe('correcciones incrementales de grupos',()=>{it('permite solo las dos rutas reales de assets',()=>{expect(fix).toContain("array_length(storage.foldername(name), 1) = 2");expect(fix).toContain("in ('covers', 'materials')");expect(fix).toContain("where g.id = (storage.foldername(name))[1]::uuid")});it('concede delivery_mode y corrige el slug de Intermedio',()=>{expect(fix).toContain('grant select (delivery_mode)');expect(fix).toContain("'python-intermedio'")})})
describe('policy final de escritura de assets',()=>{it('autoriza solo admins y rutas UUID/covers|materials sin la subconsulta cruzada',()=>{expect(storageFix).toContain("bucket_id = 'live-group-assets'");expect(storageFix).toContain('(select public.is_admin())');expect(storageFix).toContain('array_length(storage.foldername(name), 1) = 2');expect(storageFix).toContain("in ('covers', 'materials')");expect(storageFix).toContain('[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}');expect(storageFix).not.toContain('from public.live_groups')})})
describe('policy final de lectura de assets',()=>{it('permite firmar al admin o miembro mediante el helper seguro',()=>{expect(memberReadFix).toContain("bucket_id = 'live-group-assets'");expect(memberReadFix).toContain('(select public.is_admin())');expect(memberReadFix).toContain('public.is_live_group_member');expect(memberReadFix).toContain("in ('covers', 'materials')");expect(memberReadFix).not.toContain('from public.live_groups')})})
