import type { V2Design, V2Widget } from './gui-designer-v2'

export type PreviewRect={x:number;y:number;width:number;height:number}
const clamp=(n:number,min=1)=>Math.max(min,Math.round(n))
export function naturalSize(widget:V2Widget):{width:number;height:number}{
 const font=widget.fontSize??13,text=widget.text??widget.name,chars=widget.tkWidth
 if(widget.type==='Label')return{width:clamp(text.length*font*.58+8,24),height:clamp(font*1.55,22)}
 if(widget.type==='Button')return{width:clamp(text.length*font*.6+30,70),height:clamp(font*1.7+10,32)}
 if(widget.type==='Entry')return{width:clamp((chars??20)*font*.62+18,90),height:clamp(font*1.65+8,30)}
 if(widget.type==='Combobox')return{width:clamp((chars??18)*font*.62+34,100),height:clamp(font*1.65+8,30)}
 if(widget.type==='Checkbutton'||widget.type==='Radiobutton')return{width:clamp(text.length*font*.58+30,70),height:clamp(font*1.6+6,26)}
 if(widget.type==='Spinbox')return{width:clamp((chars??10)*font*.62+28,70),height:32}
 if(widget.type==='Scale')return{width:widget.length??180,height:35}
 if(widget.type==='Progressbar')return{width:widget.length??200,height:24}
 if(widget.type==='Scrollbar')return widget.orient==='horizontal'?{width:160,height:18}:{width:18,height:160}
 if(widget.type==='Separator')return widget.orient==='vertical'?{width:4,height:100}:{width:160,height:4}
 if(widget.type==='Treeview')return{width:Math.max(180,(widget.columns??[]).reduce((sum,c)=>sum+c.width,0)),height:30+(widget.tkHeight??8)*24}
 if(widget.type==='Text')return{width:clamp((chars??30)*8+16,120),height:clamp((widget.tkHeight??6)*20+12,70)}
 return{width:widget.layout.width,height:widget.layout.height}
}
function contentRect(widget:V2Widget|undefined,rect:PreviewRect):PreviewRect{const pad=widget?.padding??0,top=widget?.type==='Labelframe'?22:widget?.type==='Notebook'?34:0;return{x:rect.x+pad,y:rect.y+pad+top,width:Math.max(1,rect.width-pad*2),height:Math.max(1,rect.height-pad*2-top)}}
function pack(children:V2Widget[],area:PreviewRect,measure=(widget:V2Widget)=>naturalSize(widget)){const result=new Map<string,PreviewRect>(),sizes=new Map(children.map(w=>[w.id,measure(w)]));const cavity={...area};const verticalExpand=children.filter(w=>w.layout.expand&&['top','bottom'].includes(w.layout.side??'top')).length,horizontalExpand=children.filter(w=>w.layout.expand&&['left','right'].includes(w.layout.side??'top')).length;const fixedH=children.filter(w=>!w.layout.expand&&['top','bottom'].includes(w.layout.side??'top')).reduce((s,w)=>s+sizes.get(w.id)!.height+2*(w.layout.pady??0),0),fixedW=children.filter(w=>!w.layout.expand&&['left','right'].includes(w.layout.side??'top')).reduce((s,w)=>s+sizes.get(w.id)!.width+2*(w.layout.padx??0),0);const extraH=Math.max(0,area.height-fixedH)/Math.max(1,verticalExpand),extraW=Math.max(0,area.width-fixedW)/Math.max(1,horizontalExpand);for(const w of children){const l=w.layout,n=sizes.get(w.id)!,side=l.side??'top',px=l.padx??0,py=l.pady??0;if(side==='top'||side==='bottom'){const parcel=Math.min(cavity.height,l.expand?extraH:n.height+py*2),y=side==='top'?cavity.y:cavity.y+cavity.height-parcel,width=['x','both'].includes(l.fill??'none')?Math.max(1,cavity.width-px*2):Math.min(n.width,cavity.width-px*2),height=['y','both'].includes(l.fill??'none')?Math.max(1,parcel-py*2):Math.min(n.height,parcel-py*2);result.set(w.id,{x:cavity.x+px+(cavity.width-px*2-width)/2,y:y+py+(parcel-py*2-height)/2,width,height});if(side==='top'){cavity.y+=parcel;cavity.height-=parcel}else cavity.height-=parcel}else{const parcel=Math.min(cavity.width,l.expand?extraW:n.width+px*2),x=side==='left'?cavity.x:cavity.x+cavity.width-parcel,width=['x','both'].includes(l.fill??'none')?Math.max(1,parcel-px*2):Math.min(n.width,parcel-px*2),height=['y','both'].includes(l.fill??'none')?Math.max(1,cavity.height-py*2):Math.min(n.height,cavity.height-py*2);result.set(w.id,{x:x+px+(parcel-px*2-width)/2,y:cavity.y+py+(cavity.height-py*2-height)/2,width,height});if(side==='left'){cavity.x+=parcel;cavity.width-=parcel}else cavity.width-=parcel}}
 return result
}
function grid(children:V2Widget[],area:PreviewRect,parent?:V2Widget,measure=(widget:V2Widget)=>naturalSize(widget)){const result=new Map<string,PreviewRect>(),cols=Math.max(1,...children.map(w=>(w.layout.column??0)+(w.layout.columnspan??1))),rows=Math.max(1,...children.map(w=>(w.layout.row??0)+(w.layout.rowspan??1))),cw=Array(cols).fill(0),rh=Array(rows).fill(0);for(const w of children){const n=measure(w),c=w.layout.column??0,r=w.layout.row??0,cs=w.layout.columnspan??1,rs=w.layout.rowspan??1;for(let i=c;i<c+cs;i++)cw[i]=Math.max(cw[i],(n.width+2*(w.layout.padx??0))/cs);for(let i=r;i<r+rs;i++)rh[i]=Math.max(rh[i],(n.height+2*(w.layout.pady??0))/rs)}const colWeights=(parent?.columnWeights??'').split(',').map(Number),rowWeights=(parent?.rowWeights??'').split(',').map(Number),extraW=Math.max(0,area.width-cw.reduce((a,b)=>a+b,0)),extraH=Math.max(0,area.height-rh.reduce((a,b)=>a+b,0)),sumCW=colWeights.reduce((a,b)=>a+(b||0),0),sumRW=rowWeights.reduce((a,b)=>a+(b||0),0);cw.forEach((_,i)=>cw[i]+=sumCW?extraW*(colWeights[i]||0)/sumCW:0);rh.forEach((_,i)=>rh[i]+=sumRW?extraH*(rowWeights[i]||0)/sumRW:0);for(const w of children){const l=w.layout,n=measure(w),c=l.column??0,r=l.row??0,cs=l.columnspan??1,rs=l.rowspan??1,px=l.padx??0,py=l.pady??0,x=area.x+cw.slice(0,c).reduce((a,b)=>a+b,0),y=area.y+rh.slice(0,r).reduce((a,b)=>a+b,0),cellW=cw.slice(c,c+cs).reduce((a,b)=>a+b,0),cellH=rh.slice(r,r+rs).reduce((a,b)=>a+b,0),sticky=(l.sticky??'').toLowerCase(),width=sticky.includes('e')&&sticky.includes('w')?cellW-px*2:Math.min(n.width,cellW-px*2),height=sticky.includes('n')&&sticky.includes('s')?cellH-py*2:Math.min(n.height,cellH-py*2);result.set(w.id,{x:x+px+(sticky.includes('w')?0:sticky.includes('e')?cellW-px*2-width:(cellW-px*2-width)/2),y:y+py+(sticky.includes('n')?0:sticky.includes('s')?cellH-py*2-height:(cellH-py*2-height)/2),width:clamp(width),height:clamp(height)})}return result}
export function resolvePreviewLayout(design:V2Design){const out=new Map<string,PreviewRect>(),byParent=(id:string|null)=>design.widgets.filter(w=>w.parentId===id),measured=new Map<string,{width:number;height:number}>();const measure=(widget:V2Widget):{width:number;height:number}=>{const cached=measured.get(widget.id);if(cached)return cached;const own=naturalSize(widget),children=byParent(widget.id);if(!children.length){measured.set(widget.id,own);return own}const pad=(widget.padding??0)*2+(widget.type==='Labelframe'?22:widget.type==='Notebook'?34:0),manager=children.find(child=>child.layout.manager!=='place')?.layout.manager;let width=own.width,height=own.height;if(manager==='grid'){const cols=Math.max(1,...children.map(child=>(child.layout.column??0)+(child.layout.columnspan??1))),rows=Math.max(1,...children.map(child=>(child.layout.row??0)+(child.layout.rowspan??1))),cw=Array(cols).fill(0),rh=Array(rows).fill(0);for(const child of children){const size=measure(child),c=child.layout.column??0,r=child.layout.row??0;const cs=child.layout.columnspan??1,rs=child.layout.rowspan??1;for(let i=c;i<c+cs;i++)cw[i]=Math.max(cw[i],(size.width+2*(child.layout.padx??0))/cs);for(let i=r;i<r+rs;i++)rh[i]=Math.max(rh[i],(size.height+2*(child.layout.pady??0))/rs)}width=Math.max(width,cw.reduce((a,b)=>a+b,0)+(widget.padding??0)*2);height=Math.max(40,rh.reduce((a,b)=>a+b,0)+pad)}else{const vertical=children.filter(child=>['top','bottom'].includes(child.layout.side??'top')),horizontal=children.filter(child=>['left','right'].includes(child.layout.side??'top'));width=Math.max(width,...vertical.map(child=>measure(child).width+2*(child.layout.padx??0)),horizontal.reduce((sum,child)=>sum+measure(child).width+2*(child.layout.padx??0),0));height=Math.max(40,vertical.reduce((sum,child)=>sum+measure(child).height+2*(child.layout.pady??0),0),...horizontal.map(child=>measure(child).height+2*(child.layout.pady??0)))+pad}const result={width,height};measured.set(widget.id,result);return result};const resolve=(parent:string|null,rect:PreviewRect)=>{const parentWidget=parent?design.widgets.find(w=>w.id===parent):undefined,area=contentRect(parentWidget,rect),children=byParent(parent),managed=children.filter(w=>w.layout.manager!=='place'),manager=managed[0]?.layout.manager,resolved=manager==='grid'?grid(managed,area,parentWidget,measure):pack(managed,area,measure);for(const w of children){let child:PreviewRect;if(w.layout.manager==='place')child={x:area.x+w.layout.x,y:area.y+w.layout.y,width:w.layout.width,height:w.layout.height};else child=resolved.get(w.id)??{x:area.x,y:area.y,...naturalSize(w)};out.set(w.id,child);resolve(w.id,child)}};resolve(null,{x:0,y:25,width:design.window.width,height:design.window.height-25});return out}
