import {readFileSync} from 'node:fs'
import {describe,expect,it} from 'vitest'
import {WIDGET_REGISTRY,importGeneratedGui,newV2Design,nextV2Widget,type V2WidgetType} from './gui-designer-v2'
import {naturalSize,resolvePreviewLayout,resolvePreviewLayoutDetailed,suspiciousSiblingOverlaps} from './gui-layout'

describe('motor geométrico del Designer',()=>{
 it('measures all 18 supported widget previews without invalid bounds',()=>{const widgets=(Object.keys(WIDGET_REGISTRY) as V2WidgetType[]).map(type=>nextV2Widget(type,[],null));expect(widgets).toHaveLength(18);for(const widget of widgets){const size=naturalSize(widget);expect(size.width,widget.type).toBeGreaterThan(0);expect(size.height,widget.type).toBeGreaterThan(0)}})
 it('expands a root pack child inside the available cavity',()=>{const d=newV2Design();d.window.width=900;d.window.height=675;const main=nextV2Widget('Frame',[]);main.layout={...main.layout,manager:'pack',fill:'both',expand:true,padx:20,pady:20};d.widgets=[main];expect(resolvePreviewLayout(d).get(main.id)).toEqual({x:20,y:45,width:860,height:610})})
 it('measures character widths instead of treating them as pixels',()=>{const entry=nextV2Widget('Entry',[]),combo=nextV2Widget('Combobox',[entry]);entry.tkWidth=30;combo.tkWidth=18;expect(naturalSize(entry).width).toBeGreaterThan(200);expect(naturalSize(combo).width).toBeGreaterThan(130)})
 it('places left and right packed children at opposite edges',()=>{const d=newV2Design(),frame=nextV2Widget('Frame',[]),left=nextV2Widget('Button',[frame],frame.id),right=nextV2Widget('Button',[frame,left],frame.id);frame.layout={...frame.layout,width:800,height:80};left.layout.manager='pack';left.layout.side='left';right.layout.manager='pack';right.layout.side='right';d.widgets=[frame,left,right];const r=resolvePreviewLayout(d);expect(r.get(left.id)!.x).toBeLessThan(r.get(right.id)!.x)})
 it('distributes three expanding left-packed siblings without overlap',()=>{const d=newV2Design(),parent=nextV2Widget('Frame',[]);parent.layout={...parent.layout,width:900,height:120};const children:ReturnType<typeof nextV2Widget>[]=[];for(const name of ['uno','dos','tres']){const child=nextV2Widget('Frame',[parent,...children],parent.id);child.name=name;child.layout={...child.layout,manager:'pack',side:'left',fill:'x',expand:true};children.push(child)}d.widgets=[parent,...children];const r=resolvePreviewLayout(d),rects=children.map(child=>r.get(child.id)!);expect(rects[0].x+rects[0].width).toBeLessThanOrEqual(rects[1].x);expect(rects[1].x+rects[1].width).toBeLessThanOrEqual(rects[2].x);expect(suspiciousSiblingOverlaps(d,r)).toEqual([])})
 it('keeps place coordinates local inside a parent allocated by pack',()=>{const d=newV2Design(),main=nextV2Widget('Frame',[]),footer=nextV2Widget('Frame',[main],main.id),button=nextV2Widget('Button',[main,footer],footer.id);main.layout={...main.layout,manager:'pack',fill:'both',expand:true,padx:20,pady:20};footer.layout={...footer.layout,manager:'pack',fill:'x'};button.layout={...button.layout,manager:'place',x:30,y:12,width:100,height:35};d.widgets=[main,footer,button];const detail=resolvePreviewLayoutDetailed(d),parent=detail.absolute.get(footer.id)!,child=detail.absolute.get(button.id)!;expect(detail.local.get(button.id)).toMatchObject({x:30,y:12});expect(child.x).toBe(parent.x+30);expect(child.y).toBe(parent.y+12)})
 it('lays out only the active Notebook tab and preserves inactive children',()=>{const d=newV2Design(),notebook=nextV2Widget('Notebook',[]),first=nextV2Widget('Button',[notebook],notebook.id),second=nextV2Widget('Button',[notebook,first],notebook.id);notebook.tabs=[{id:'general',text:'General'},{id:'config',text:'Configuración'}];notebook.activeTabId='general';first.parentTabId='general';second.parentTabId='config';first.layout.manager='pack';second.layout.manager='pack';d.widgets=[notebook,first,second];const r=resolvePreviewLayout(d);expect(r.has(first.id)).toBe(true);expect(r.has(second.id)).toBe(false);expect(d.widgets).toContain(second)})
 it('measures vertical Scale and Progressbar by orientation',()=>{const scale=nextV2Widget('Scale',[]),progress=nextV2Widget('Progressbar',[scale]);scale.orient='vertical';scale.length=150;progress.orient='vertical';progress.length=140;expect(naturalSize(scale).height).toBeGreaterThan(naturalSize(scale).width);expect(naturalSize(progress).height).toBeGreaterThan(naturalSize(progress).width)})
 it('honors grid spans, sticky axes and configured weights',()=>{const d=newV2Design(),frame=nextV2Widget('Frame',[]),wide=nextV2Widget('Entry',[frame],frame.id),fill=nextV2Widget('Frame',[frame,wide],frame.id);frame.layout={...frame.layout,width:600,height:300};frame.columnWeights='1, 3';frame.rowWeights='1, 2';wide.layout={...wide.layout,manager:'grid',row:0,column:0,columnspan:2,sticky:'ew',padx:10,pady:5};fill.layout={...fill.layout,manager:'grid',row:1,column:1,sticky:'nsew',padx:4,pady:4};d.widgets=[frame,wide,fill];const r=resolvePreviewLayout(d),f=r.get(frame.id)!,w=r.get(wide.id)!,x=r.get(fill.id)!;expect(w.width).toBeGreaterThan(f.width*.8);expect(x.x).toBeGreaterThan(f.x+f.width*.2);expect(x.width).toBeGreaterThan(f.width*.45);expect(x.height).toBeGreaterThan(f.height*.4)})
 it('resolves the complete student panel fixture without compressed controls',()=>{const source=readFileSync(new URL('./fixtures/panel-estudiantes.py',import.meta.url),'utf8'),d=importGeneratedGui(source)!,r=resolvePreviewLayout(d),byName=new Map(d.widgets.map(w=>[w.name,w]));expect(d.window.theme).toBe('superhero');expect(d.widgets).toHaveLength(28);const main=r.get(byName.get('main')!.id)!,header=r.get(byName.get('header')!.id)!,form=r.get(byName.get('formulario')!.id)!,title=r.get(byName.get('titulo')!.id)!,button=r.get(byName.get('btn_nuevo')!.id)!,entry=r.get(byName.get('entry_nombre')!.id)!,combo=r.get(byName.get('combo_seccion')!.id)!,table=r.get(byName.get('panel_tabla')!.id)!;expect(main.width).toBeGreaterThan(800);expect(header.width).toBeGreaterThan(main.width*.9);expect(title.x).toBeLessThan(button.x);expect(form.width).toBeGreaterThan(main.width*.9);expect(entry.width).toBeGreaterThan(200);expect(combo.width).toBeGreaterThan(130);expect(table.width).toBeGreaterThan(main.width*.9);expect(table.height).toBeGreaterThan(150)})
 it.each([['sistema-reservas-regression.py','superhero',23],['panel-administrativo-regression.py','darkly',29]] as const)('resolves complex fixture %s without managed sibling overlaps',(file,theme,widgetCount)=>{const source=readFileSync(new URL(`./fixtures/${file}`,import.meta.url),'utf8'),d=importGeneratedGui(source)!,r=resolvePreviewLayout(d);expect(d.window.theme).toBe(theme);expect(d.widgets).toHaveLength(widgetCount);expect([...r.values()].every(rect=>Number.isFinite(rect.x)&&Number.isFinite(rect.y)&&rect.width>0&&rect.height>0)).toBe(true);expect(suspiciousSiblingOverlaps(d,r)).toEqual([])})
})
