"""Datos del proyecto del Módulo 3 de Python Práctico."""

SOLICITUDES_PENDIENTES = [
    {
        "id": "SOP-001",
        "titulo": "Video de una lección no carga",
        "categoria": "contenido",
        "prioridad": "normal",
        "responsable": "Ana",
        "etiquetas": ["curso", "video"],
        "minutos_estimados": 25,
    },
    {
        "id": "SOP-002",
        "titulo": "Factura con datos incorrectos",
        "categoria": "facturación",
        "prioridad": "alta",
        "responsable": "Luis",
        "etiquetas": ["pago", "factura"],
        "minutos_estimados": 20,
    },
    {
        "id": "SOP-003",
        "titulo": "No puedo cambiar mi nombre",
        "categoria": "cuenta",
        "prioridad": "normal",
        "responsable": "María",
        "etiquetas": ["perfil", "datos"],
        "minutos_estimados": 15,
    },
    {
        "id": "SOP-004",
        "titulo": "Error al iniciar sesión",
        "categoria": "acceso",
        "prioridad": "urgente",
        "responsable": "Carlos",
        "etiquetas": ["inicio de sesión", "bloqueo"],
        "minutos_estimados": 10,
    },
    {
        "id": "SOP-005",
        "titulo": "Ejercicio marcado como incompleto",
        "categoria": "contenido",
        "prioridad": "alta",
        "responsable": "Ana",
        "etiquetas": ["curso", "ejercicio"],
        "minutos_estimados": 30,
    },
    {
        "id": "SOP-006",
        "titulo": "No aparece el certificado",
        "categoria": "certificado",
        "prioridad": "normal",
        "responsable": "Luis",
        "etiquetas": ["certificado", "finalización"],
        "minutos_estimados": 20,
    },
]

SOLICITUDES_NUEVAS = [
    {
        "id": "SOP-007",
        "titulo": "Correo de recuperación no llega",
        "categoria": "acceso",
        "prioridad": "normal",
        "responsable": "María",
        "etiquetas": ["correo", "recuperación"],
        "minutos_estimados": 15,
    },
    {
        "id": "SOP-008",
        "titulo": "La página se cierra inesperadamente",
        "categoria": "técnico",
        "prioridad": "alta",
        "responsable": "Carlos",
        "etiquetas": ["navegador", "error"],
        "minutos_estimados": 35,
    },
    {
        "id": "SOP-009",
        "titulo": "Certificado muestra un curso incompleto",
        "categoria": "certificado",
        "prioridad": "alta",
        "responsable": "Ana",
        "etiquetas": ["certificado", "curso"],
        "minutos_estimados": 25,
    },
    {
        "id": "SOP-010",
        "titulo": "Texto de una lección está cortado",
        "categoria": "contenido",
        "prioridad": "normal",
        "responsable": "Luis",
        "etiquetas": ["curso", "texto"],
        "minutos_estimados": 15,
    },
    {
        "id": "SOP-011",
        "titulo": "Cobro duplicado",
        "categoria": "facturación",
        "prioridad": "urgente",
        "responsable": "María",
        "etiquetas": ["pago", "duplicado"],
        "minutos_estimados": 20,
    },
    {
        "id": "SOP-012",
        "titulo": "El editor no guarda el progreso",
        "categoria": "técnico",
        "prioridad": "normal",
        "responsable": "Carlos",
        "etiquetas": ["editor", "progreso"],
        "minutos_estimados": 30,
    },
    {
        "id": "SOP-013",
        "titulo": "Cuenta bloqueada antes de evaluación",
        "categoria": "acceso",
        "prioridad": "urgente",
        "responsable": "Ana",
        "etiquetas": ["bloqueo", "evaluación"],
        "minutos_estimados": 10,
    },
    {
        "id": "SOP-014",
        "titulo": "Preferencias de cuenta no se actualizan",
        "categoria": "cuenta",
        "prioridad": "normal",
        "responsable": "Carlos",
        "etiquetas": ["perfil", "preferencias"],
        "minutos_estimados": 20,
    },
]

RESPONSABLES = ["Ana", "Luis", "María", "Carlos"]
TURNOS = ["mañana", "tarde"]
