import { expect, test } from '@playwright/test'

test('desktop Más is accessible and keeps all reorganized destinations',async({page})=>{
  await page.goto('/')
  const more=page.getByRole('button',{name:/Más/})
  await more.click()
  await expect(more).toHaveAttribute('aria-expanded','true')
  const menu=page.getByRole('menu')
  await expect(menu.getByRole('menuitem',{name:/Certificados/})).toHaveAttribute('href','/certificados')
  await expect(menu.getByRole('menuitem',{name:/Beneficios/})).toHaveAttribute('href','/#beneficios')
  await expect(menu.getByRole('menuitem',{name:/Términos/})).toHaveAttribute('href','/terminos-y-condiciones')
  await page.keyboard.press('Escape')
  await expect(more).toHaveAttribute('aria-expanded','false')
  await more.click();await page.getByRole('menuitem',{name:/Certificados/}).click()
  await expect(page).toHaveURL(/\/certificados$/)
  await expect(page.getByRole('heading',{name:'Verifica tu certificado',level:1})).toBeVisible()
  await page.goto('/experiencia-profesional');await expect(page.getByRole('heading',{name:/Programa de Experiencia Profesional/,level:1})).toBeVisible()
  await page.goto('/terminos-y-condiciones');await expect(page.getByRole('heading',{name:/Términos y Condiciones/,level:1})).toBeVisible()
})

test('manual verification supports Enter, normalization, empty and missing states',async({page})=>{
  await page.goto('/certificados')
  const input=page.getByLabel('Código del certificado')
  await page.getByRole('button',{name:'Verificar certificado'}).click()
  await expect(page.getByText('Ingresa el código del certificado.',{exact:true})).toBeVisible()
  await input.fill('  coa-pyb-2026-0001  ');await input.press('Enter')
  await expect(page).toHaveURL(/\/certificados\/COA-PYB-2026-0001$/)
  const result=page.getByTestId('certificate-result')
  await expect(result).toContainText('Certificado verificado')
  await expect(result).toContainText('Python Básico')
  await expect(result).toContainText('Estado: Válido')
  await input.fill('COA-NO-EXISTE');await input.press('Enter')
  await expect(page.getByRole('status')).toContainText('No encontramos un certificado con ese código')
  await expect(input).toHaveValue('COA-NO-EXISTE')
})

test('direct URLs verify valid and unknown codes and mobile navigation stays usable',async({page})=>{
  await page.goto('/certificados/coa-pyb-2026-0001')
  await expect(page).toHaveURL(/\/certificados\/COA-PYB-2026-0001$/)
  await expect(page.getByTestId('certificate-result')).toContainText('COA-PYB-2026-0001')
  await page.reload();await expect(page.getByTestId('certificate-result')).toContainText('COA-PYB-2026-0001')
  const other=await page.context().newPage();await other.goto('/certificados/COA-PYB-2026-0001');await expect(other.getByTestId('certificate-result')).toBeVisible();await other.close()
  await page.goto('/certificados');await page.getByLabel('Código del certificado').fill('COA-PYB-2026-0001');await page.getByLabel('Código del certificado').press('Enter');await expect(page).toHaveURL(/COA-PYB-2026-0001$/)
  await page.goBack();await expect(page).toHaveURL(/\/certificados$/);await expect(page.getByTestId('certificate-result')).toHaveCount(0)
  await page.goForward();await expect(page.getByTestId('certificate-result')).toContainText('COA-PYB-2026-0001')
  await page.goto('/certificados/COA-NO-EXISTE')
  await expect(page.getByRole('status')).toContainText('No encontramos')
  await page.setViewportSize({width:390,height:844});await page.goto('/')
  await page.getByRole('button',{name:'Abrir menú'}).click()
  const mobile=page.locator('header nav').last()
  await expect(mobile.getByRole('link',{name:'Certificados',exact:true})).toBeVisible()
  await expect(mobile.getByRole('link',{name:'Beneficios',exact:true})).toBeVisible()
  await expect(mobile.getByRole('link',{name:'Términos y condiciones',exact:true})).toBeVisible()
  await expect(mobile.getByRole('link',{name:'Experiencia',exact:true})).toBeVisible()
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBe(true)
})
