import { expect, test, type Page } from '@playwright/test'

async function start(page: Page) {
  await page.goto('/ide')
  const welcome = page.getByRole('button', { name: 'Comenzar', exact: true })
  if (await welcome.isVisible()) await welcome.click()
  await expect(page.getByText('Python listo', { exact: true })).toBeVisible({ timeout: 100000 })
  await expect(page.locator('.monaco-editor')).toBeVisible({ timeout: 45000 })
}
async function edit(page: Page, code: string) {
  await page.locator('.monaco-editor textarea').focus()
  await page.keyboard.press('Control+A')
  await page.keyboard.insertText(code)
}

test('COA GUI dialogs wait, validate input and return Python values', async ({ page }) => {
  await start(page)
  await edit(page, 'import coa_gui as gui\nname = gui.askstring("Nombre", "Ingrese su nombre")\nprint("Hola", name)')
  await page.getByRole('button', { name: 'Ejecutar', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Nombre' })
  await expect(dialog).toBeVisible()
  await expect(page.getByTestId('python-output')).not.toContainText('Hola Ana')
  await dialog.getByLabel('Respuesta').fill('Ana')
  await dialog.getByRole('button', { name: 'Aceptar' }).click()
  await expect(page.getByTestId('python-output')).toContainText('Hola Ana')

  await edit(page, 'import coa_gui as gui\nage = gui.askinteger("Edad", "Ingrese su edad")\nprint(type(age).__name__, age)')
  await page.getByRole('button', { name: 'Ejecutar', exact: true }).click()
  const integer = page.getByRole('dialog', { name: 'Edad' })
  await integer.getByLabel('Respuesta').fill('veinte')
  await integer.getByRole('button', { name: 'Aceptar' }).click()
  await expect(integer.getByRole('alert')).toContainText('número entero')
  await integer.getByLabel('Respuesta').fill('20')
  await integer.getByRole('button', { name: 'Aceptar' }).click()
  await expect(page.getByTestId('python-output')).toContainText('int 20')

  await edit(page, 'import coa_gui as gui\nanswer = gui.askyesno("Salir", "¿Desea salir?")\nprint(answer)')
  await page.getByRole('button', { name: 'Ejecutar', exact: true }).click()
  const question = page.getByRole('dialog', { name: 'Salir' })
  await question.getByRole('button', { name: 'No', exact: true }).click()
  await expect(page.getByTestId('python-output')).toContainText('False')

  await edit(page, 'import coa_gui as gui\ngui.showinfo("Información", "Hola desde COA GUI")\nprint("cerrado")')
  await page.getByRole('button', { name: 'Ejecutar', exact: true }).click()
  const information = page.getByRole('dialog', { name: 'Información' })
  await expect(page.getByTestId('python-output')).not.toContainText('cerrado')
  await information.getByRole('button', { name: 'Aceptar' }).click()
  await expect(page.getByTestId('python-output')).toContainText('cerrado')
})

test('editor export appears only for COA GUI and preserves console and source', async ({ page, context }) => {
  await context.grantPermissions(['clipboard-read', 'clipboard-write'])
  await start(page)
  await edit(page, 'print("salida previa")')
  await expect(page.getByRole('button', { name: 'Exportar a Tkinter' })).toHaveCount(0)
  await page.getByRole('button', { name: 'Ejecutar', exact: true }).click()
  await expect(page.getByTestId('python-output')).toContainText('salida previa')
  const source = 'import coa_gui as gui\n\ndef save():\n    if True:\n        gui.showinfo("Listo", "Guardado")\nwindow = gui.Tk()'
  await edit(page, source)
  await page.locator('.monaco-editor textarea').focus()
  await page.keyboard.press('Control+A')
  await page.keyboard.press('Control+C')
  const sourceBeforeExport = await page.evaluate(() => navigator.clipboard.readText())
  await page.getByRole('button', { name: 'Exportar a Tkinter' }).click()
  const generated = page.getByTestId('editor-tkinter-code')
  await expect(generated).toContainText('import tkinter as tk')
  await expect(generated).toContainText('from tkinter import messagebox')
  await expect(generated).toContainText('def save():')
  await expect(generated).toContainText('messagebox.showinfo')
  await expect(page.getByTestId('python-output')).toContainText('salida previa')
  await page.getByRole('button', { name: 'Cerrar código tkinter generado' }).click()
  await expect(generated).toHaveCount(0)
  await page.locator('.monaco-editor textarea').focus()
  await page.keyboard.press('Control+A')
  await page.keyboard.press('Control+C')
  await expect.poll(() => page.evaluate(() => navigator.clipboard.readText())).toBe(sourceBeforeExport)
})

test('Builder inserts a popup with the existing cursor indentation', async ({ page }) => {
  await start(page)
  await edit(page, 'def register():\n    pass')
  await page.locator('.monaco-editor textarea').focus()
  await page.keyboard.press('Control+End')
  await page.keyboard.press('Home')
  await page.getByRole('button', { name: 'Nivel 2' }).click()
  await page.getByRole('button', { name: /^Pedir texto/ }).click()
  await page.getByLabel('Variable donde guardar resultado').fill('nombre')
  await page.getByRole('button', { name: 'Agregar código' }).click()
  await expect(page.locator('.monaco-editor')).toContainText('    nombre = gui.askstring(')
})

test('dialog appearance, position and persistence are configurable', async ({ page }) => {
  await start(page)
  await page.getByRole('button', { name: 'Configuración' }).click()
  await page.getByRole('button', { name: /Ventanas/ }).click()
  const themed = page.getByLabel('Color según el tema')
  const position = page.getByLabel('Posición de ventanas emergentes')
  await expect(themed).toBeChecked()
  await expect(position).toHaveValue('center')
  await page.getByRole('button', { name: 'Probar ventana' }).click()
  let modal = page.getByRole('dialog', { name: 'Información' })
  const centered = await modal.boundingBox()
  const viewport = page.viewportSize()!
  expect(Math.abs((centered!.x + centered!.width / 2) - viewport.width / 2)).toBeLessThan(4)
  expect(Math.abs((centered!.y + centered!.height / 2) - viewport.height / 2)).toBeLessThan(4)
  await modal.getByRole('button', { name: 'Aceptar' }).click()

  for (const value of ['top','bottom','left','right','top-left','top-right','bottom-left','bottom-right']) {
    await position.selectOption(value)
    await page.getByRole('button', { name: 'Probar ventana' }).click()
    modal = page.getByRole('dialog', { name: 'Información' })
    const box = await modal.boundingBox()
    expect(box!.x).toBeGreaterThanOrEqual(0)
    expect(box!.y).toBeGreaterThanOrEqual(0)
    expect(box!.x + box!.width).toBeLessThanOrEqual(viewport.width)
    expect(box!.y + box!.height).toBeLessThanOrEqual(viewport.height)
    await modal.getByRole('button', { name: 'Aceptar' }).click()
  }
  await themed.uncheck()
  await page.getByRole('button', { name: 'Probar ventana' }).click()
  modal = page.getByRole('dialog', { name: 'Información' })
  await expect(modal).toHaveClass(/coa-dialog-neutral/)
  expect(await modal.evaluate((element) => getComputedStyle(element).backgroundColor)).toMatch(/rgb\((?:24[0-9]|25[0-5])/)
  await modal.getByRole('button', { name: 'Aceptar' }).click()
  await page.reload()
  await page.getByRole('button', { name: 'Configuración' }).click()
  await page.getByRole('button', { name: /Ventanas/ }).click()
  await expect(page.getByLabel('Color según el tema')).not.toBeChecked()
  await expect(page.getByLabel('Posición de ventanas emergentes')).toHaveValue('bottom-right')
})

test('a corner dialog remains fully visible on mobile', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 700 })
  await start(page)
  await page.getByRole('button', { name: 'Configuración' }).click()
  await page.getByRole('button', { name: /Ventanas/ }).click()
  await page.getByLabel('Posición de ventanas emergentes').selectOption('bottom-right')
  await page.getByRole('button', { name: 'Probar ventana' }).click()
  const box = await page.getByRole('dialog', { name: 'Información' }).boundingBox()
  expect(box!.x).toBeGreaterThanOrEqual(0)
  expect(box!.y).toBeGreaterThanOrEqual(0)
  expect(box!.x + box!.width).toBeLessThanOrEqual(390)
  expect(box!.y + box!.height).toBeLessThanOrEqual(700)
})
