import { expect, test, type Page } from '@playwright/test'

async function start(page: Page) {
  await page.goto('/ide')
  const welcome = page.getByRole('button', { name: 'Comenzar', exact: true })
  if (await welcome.isVisible()) await welcome.click()
  await expect(page.getByText('Python listo', { exact: true })).toBeVisible({ timeout: 100000 })
  await expect(page.locator('.monaco-editor')).toBeVisible({ timeout: 45000 })
}
async function edit(page: Page, code: string) {
  await page.locator('.monaco-editor textarea').focus()
  await page.keyboard.press('Control+A')
  await page.keyboard.insertText(code)
}

test('COA GUI dialogs wait, validate input and return Python values', async ({ page }) => {
  await start(page)
  await edit(page, 'import coa_gui as gui\nname = gui.askstring("Nombre", "Ingrese su nombre")\nprint("Hola", name)')
  await page.getByRole('button', { name: 'Ejecutar', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Nombre' })
  await expect(dialog).toBeVisible()
  await expect(page.getByTestId('python-output')).not.toContainText('Hola Ana')
  await dialog.getByLabel('Respuesta').fill('Ana')
  await dialog.getByRole('button', { name: 'Aceptar' }).click()
  await expect(page.getByTestId('python-output')).toContainText('Hola Ana')

  await edit(page, 'import coa_gui as gui\nage = gui.askinteger("Edad", "Ingrese su edad")\nprint(type(age).__name__, age)')
  await page.getByRole('button', { name: 'Ejecutar', exact: true }).click()
  const integer = page.getByRole('dialog', { name: 'Edad' })
  await integer.getByLabel('Respuesta').fill('veinte')
  await integer.getByRole('button', { name: 'Aceptar' }).click()
  await expect(integer.getByRole('alert')).toContainText('número entero')
  await integer.getByLabel('Respuesta').fill('20')
  await integer.getByRole('button', { name: 'Aceptar' }).click()
  await expect(page.getByTestId('python-output')).toContainText('int 20')

  await edit(page, 'import coa_gui as gui\nanswer = gui.askyesno("Salir", "¿Desea salir?")\nprint(answer)')
  await page.getByRole('button', { name: 'Ejecutar', exact: true }).click()
  const question = page.getByRole('dialog', { name: 'Salir' })
  await question.getByRole('button', { name: 'No', exact: true }).click()
  await expect(page.getByTestId('python-output')).toContainText('False')

  await edit(page, 'import coa_gui as gui\ngui.showinfo("Información", "Hola desde COA GUI")\nprint("cerrado")')
  await page.getByRole('button', { name: 'Ejecutar', exact: true }).click()
  const information = page.getByRole('dialog', { name: 'Información' })
  await expect(page.getByTestId('python-output')).not.toContainText('cerrado')
  await information.getByRole('button', { name: 'Aceptar' }).click()
  await expect(page.getByTestId('python-output')).toContainText('cerrado')
})

test('editor export appears only for COA GUI and preserves console and source', async ({ page, context }) => {
  await context.grantPermissions(['clipboard-read', 'clipboard-write'])
  await start(page)
  await edit(page, 'print("salida previa")')
  await expect(page.getByRole('button', { name: 'Exportar a Tkinter' })).toHaveCount(0)
  await page.getByRole('button', { name: 'Ejecutar', exact: true }).click()
  await expect(page.getByTestId('python-output')).toContainText('salida previa')
  const source = 'import coa_gui as gui\n\ndef save():\n    if True:\n        gui.showinfo("Listo", "Guardado")\nwindow = gui.Tk()'
  await edit(page, source)
  await page.locator('.monaco-editor textarea').focus()
  await page.keyboard.press('Control+A')
  await page.keyboard.press('Control+C')
  const sourceBeforeExport = await page.evaluate(() => navigator.clipboard.readText())
  await page.getByRole('button', { name: 'Exportar a Tkinter' }).click()
  const generated = page.getByTestId('editor-tkinter-code')
  await expect(generated).toContainText('import tkinter as tk')
  await expect(generated).toContainText('from tkinter import messagebox')
  await expect(generated).toContainText('def save():')
  await expect(generated).toContainText('messagebox.showinfo')
  await expect(page.getByTestId('python-output')).toContainText('salida previa')
  await page.getByRole('button', { name: 'Cerrar código tkinter generado' }).click()
  await expect(generated).toHaveCount(0)
  await page.locator('.monaco-editor textarea').focus()
  await page.keyboard.press('Control+A')
  await page.keyboard.press('Control+C')
  await expect.poll(() => page.evaluate(() => navigator.clipboard.readText())).toBe(sourceBeforeExport)
})

test('Builder inserts a popup with the existing cursor indentation', async ({ page }) => {
  await start(page)
  await edit(page, 'def register():\n    pass')
  await page.locator('.monaco-editor textarea').focus()
  await page.keyboard.press('Control+End')
  await page.keyboard.press('Home')
  await page.getByRole('button', { name: 'Nivel 2' }).click()
  await page.getByRole('button', { name: /^Pedir texto/ }).click()
  await page.getByLabel('Variable donde guardar resultado').fill('nombre')
  await page.getByRole('button', { name: 'Agregar código' }).click()
  await expect(page.locator('.monaco-editor')).toContainText('    nombre = gui.askstring(')
})
