import { expect, test } from '@playwright/test'

test('Designer V2 recovers a persisted cyclic hierarchy without clearing browser data', async ({ page }) => {
  await page.goto('/ide')
  const welcome = page.getByRole('button', { name: 'Comenzar', exact: true })
  if (await welcome.isVisible()) await welcome.click()
  await expect(page.getByRole('button', { name: 'Diseñador', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Diseñador', exact: true }).click()
  await page.locator('.gui-palette').getByRole('button', { name: 'Frame', exact: true }).click()
  await page.getByRole('button', { name: 'Guardar diseño' }).click()
  await page.waitForTimeout(300)
  await page.evaluate(async () => {
    const db = await new Promise<IDBDatabase>((resolve, reject) => { const request=indexedDB.open('coa-python-ide',1);request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error) })
    const project = await new Promise<Record<string, unknown>>((resolve, reject) => { const request=db.transaction('workspace').objectStore('workspace').get('project');request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error) })
    project.guiDesign = { schemaVersion:2, window:{title:'Corrupto',width:500,height:400,framework:'ttkbootstrap',theme:'darkly',background:'#222222',exportMode:'class'}, widgets:[{id:'a',type:'Frame',name:'a',parentId:'b',layout:{manager:'place',x:0,y:0,width:100,height:100}},{id:'b',type:'Frame',name:'b',parentId:'a',layout:{manager:'place',x:0,y:0,width:100,height:100}}] }
    await new Promise<void>((resolve, reject) => { const transaction=db.transaction('workspace','readwrite');transaction.objectStore('workspace').put(project,'project');transaction.oncomplete=()=>resolve();transaction.onerror=()=>reject(transaction.error) })
    db.close()
  })
  await page.reload()
  await page.getByRole('button', { name: 'Diseñador', exact: true }).click()
  await expect(page.getByLabel('Área de diseño')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Limpiar diseño' })).toBeVisible()
  await page.getByRole('button', { name: 'Exportar a ttkbootstrap' }).click()
  await expect(page.getByTestId('gui-code')).toContainText('ttk.Window')
})

test('Designer V2 builds hierarchy, configures widgets and round-trips ttkbootstrap', async ({ page }) => {
  await page.goto('/ide')
  const welcome = page.getByRole('button', { name: 'Comenzar', exact: true })
  if (await welcome.isVisible()) await welcome.click()
  await page.getByRole('button', { name: 'Diseñador', exact: true }).click()
  const palette = page.locator('.gui-palette')
  const properties = page.locator('.gui-properties')
  const canvas = page.getByLabel('Área de diseño')

  await palette.getByRole('button', { name: 'Frame', exact: true }).click()
  await properties.getByLabel('Nombre de variable').fill('header')
  await palette.getByText('Entrada', { exact: true }).click()
  await palette.getByRole('button', { name: 'Combobox', exact: true }).click()
  await properties.getByLabel('Nombre de variable').fill('categoria')
  await properties.getByRole('textbox',{name:'Opción 1',exact:true}).fill('Todos'); await properties.getByRole('textbox',{name:'Opción 2',exact:true}).fill('Libros'); await properties.getByRole('button',{name:'+ Agregar opción'}).click(); await properties.getByRole('textbox',{name:'Opción 3',exact:true}).fill('Tecnología')
  await properties.getByLabel('Bootstyle').selectOption('info')
  await expect(palette.getByRole('button', { name: 'Combobox — categoria' })).toBeVisible()
  await expect(canvas.getByRole('button', { name: 'Combobox categoria' })).toContainText('Todos')

  await palette.getByText('Datos', { exact: true }).click()
  await palette.getByRole('button', { name: 'Tabla', exact: true }).click()
  await properties.getByLabel('Nombre de variable').fill('productos')
  await properties.getByLabel('Columnas').fill('producto|Producto|160|w\ncantidad|Cant.|70|center\nprecio|Precio|90|e')
  await palette.getByRole('button', { name: 'Ventana — root' }).click()
  await palette.getByRole('button', { name: 'Pestañas', exact: true }).click()
  await properties.getByLabel('Pestañas').fill('Catálogo, Carrito')

  await palette.getByRole('button', { name: 'Ventana — root' }).click()
  await palette.getByLabel('Framework').selectOption('ttkbootstrap')
  await palette.getByLabel('Tema').selectOption('cyborg')
  await palette.getByLabel('Estructura').selectOption('class')
  await page.getByRole('button', { name: 'Exportar a ttkbootstrap' }).click()
  const code = page.getByTestId('gui-code')
  await expect(code).toContainText('import ttkbootstrap as ttk')
  await expect(code).toContainText('ttk.Window(themename="cyborg")')
  await expect(code).toContainText('self.categoria = ttk.Combobox(self.header')
  await expect(code).toContainText('self.productos.heading("producto"')
  const generated = await code.textContent()
  await page.getByRole('button', { name: 'Cerrar código generado' }).click()

  await palette.getByRole('button', { name: 'Guardar diseño' }).click()
  await page.reload()
  await page.getByRole('button', { name: 'Diseñador', exact: true }).click()
  await expect(page.getByLabel('Área de diseño').getByRole('button', { name: 'Combobox categoria' })).toBeVisible()
  await expect(page.locator('.gui-palette').getByLabel('Tema')).toHaveValue('cyborg')

  await page.getByRole('button', { name: 'Importar código COA GUI / Tkinter' }).click()
  const dialog = page.getByRole('dialog', { name: 'Importar código' })
  await dialog.getByLabel('Código COA GUI').fill(generated ?? '')
  await dialog.getByRole('button', { name: 'Cargar en diseñador' }).click()
  await page.getByRole('dialog', { name: 'Reemplazar diseño actual' }).getByRole('button', { name: 'Importar' }).click()
  await expect(page.getByLabel('Área de diseño').getByRole('button', { name: 'Combobox categoria' })).toBeVisible()
  await page.locator('.gui-palette').getByRole('button', { name: 'Expandir header' }).click()
  await expect(page.locator('.gui-palette').getByRole('button', { name: 'Combobox — categoria' })).toBeVisible()
})

test('Designer V2 supports direct resize, numeric drafts and live visual properties',async({page})=>{await page.goto('/ide');const welcome=page.getByRole('button',{name:'Comenzar',exact:true});if(await welcome.isVisible())await welcome.click();await page.getByRole('button',{name:'Diseñador',exact:true}).click();const palette=page.locator('.gui-palette'),properties=page.locator('.gui-properties');await palette.getByRole('button',{name:'Ventana — root'}).click();await palette.getByLabel('Ancho').fill('900');await palette.getByLabel('Ancho').press('Enter');await palette.getByLabel('Framework').selectOption('ttkbootstrap');await palette.getByLabel('Tema').selectOption('superhero');await expect(page.getByLabel('Área de diseño')).toContainText('superhero');await palette.getByRole('button',{name:'Label',exact:true}).click();await properties.getByLabel('Texto',{exact:true}).fill('Título visual');await properties.locator('label').filter({hasText:/^FuenteArial/}).locator('select').selectOption('Arial');await properties.getByLabel('Tamaño de fuente').fill('24');await properties.getByLabel('Tamaño de fuente').press('Enter');await properties.getByText('Negrita').click();const label=page.getByRole('button',{name:/Label label/});await expect(label).toHaveCSS('font-size','24px');const before=await label.boundingBox();const handle=label.locator('.gui-resize.se');const box=await handle.boundingBox();if(!before||!box)throw new Error('No se encontraron handles');await page.mouse.move(box.x+3,box.y+3);await page.mouse.down();await page.mouse.move(box.x+63,box.y+43);await page.mouse.up();const after=await label.boundingBox();expect(after!.width).toBeGreaterThan(before.width+30);await palette.getByText('Entrada',{exact:true}).click();await palette.getByRole('button',{name:'Combobox',exact:true}).click();await properties.getByRole('button',{name:'+ Agregar opción'}).click();await properties.getByRole('textbox',{name:'Opción 3',exact:true}).fill('Pequeño');await expect(page.getByRole('button',{name:/Combobox combo/})).toContainText('Opción 1')})
