import { expect, test } from '@playwright/test'

test('Designer V2 builds hierarchy, configures widgets and round-trips ttkbootstrap', async ({ page }) => {
  await page.goto('/ide')
  const welcome = page.getByRole('button', { name: 'Comenzar', exact: true })
  if (await welcome.isVisible()) await welcome.click()
  await page.getByRole('button', { name: 'Diseñador', exact: true }).click()
  const palette = page.locator('.gui-palette')
  const properties = page.locator('.gui-properties')
  const canvas = page.getByLabel('Área de diseño')

  await palette.getByRole('button', { name: 'Frame', exact: true }).click()
  await properties.getByLabel('Nombre de variable').fill('header')
  await palette.getByText('Entrada', { exact: true }).click()
  await palette.getByRole('button', { name: 'Combobox', exact: true }).click()
  await properties.getByLabel('Nombre de variable').fill('categoria')
  await properties.getByLabel('Valores').fill('Todos, Libros, Tecnología')
  await properties.getByLabel('Bootstyle').selectOption('info')
  await expect(palette.getByRole('button', { name: 'Combobox — categoria' })).toBeVisible()
  await expect(canvas.getByRole('button', { name: 'Combobox categoria' })).toContainText('Todos')

  await palette.getByText('Datos', { exact: true }).click()
  await palette.getByRole('button', { name: 'Tabla', exact: true }).click()
  await properties.getByLabel('Nombre de variable').fill('productos')
  await properties.getByLabel('Columnas').fill('producto|Producto|160|w\ncantidad|Cant.|70|center\nprecio|Precio|90|e')
  await palette.getByRole('button', { name: 'Ventana — root' }).click()
  await palette.getByRole('button', { name: 'Pestañas', exact: true }).click()
  await properties.getByLabel('Pestañas').fill('Catálogo, Carrito')

  await palette.getByRole('button', { name: 'Ventana — root' }).click()
  await palette.getByLabel('Framework').selectOption('ttkbootstrap')
  await palette.getByLabel('Tema').selectOption('cyborg')
  await palette.getByLabel('Estructura').selectOption('class')
  await page.getByRole('button', { name: 'Exportar a ttkbootstrap' }).click()
  const code = page.getByTestId('gui-code')
  await expect(code).toContainText('import ttkbootstrap as ttk')
  await expect(code).toContainText('ttk.Window(themename="cyborg")')
  await expect(code).toContainText('self.categoria = ttk.Combobox(self.header')
  await expect(code).toContainText('self.productos.heading("producto"')
  const generated = await code.textContent()
  await page.getByRole('button', { name: 'Cerrar código generado' }).click()

  await palette.getByRole('button', { name: 'Guardar diseño' }).click()
  await page.reload()
  await page.getByRole('button', { name: 'Diseñador', exact: true }).click()
  await expect(page.getByLabel('Área de diseño').getByRole('button', { name: 'Combobox categoria' })).toBeVisible()
  await expect(page.locator('.gui-palette').getByLabel('Tema')).toHaveValue('cyborg')

  await page.getByRole('button', { name: 'Importar código COA GUI / Tkinter' }).click()
  const dialog = page.getByRole('dialog', { name: 'Importar código' })
  await dialog.getByLabel('Código COA GUI').fill(generated ?? '')
  await dialog.getByRole('button', { name: 'Cargar en diseñador' }).click()
  await page.getByRole('dialog', { name: 'Reemplazar diseño actual' }).getByRole('button', { name: 'Importar' }).click()
  await expect(page.getByLabel('Área de diseño').getByRole('button', { name: 'Combobox categoria' })).toBeVisible()
  await page.locator('.gui-palette').getByRole('button', { name: 'Expandir header' }).click()
  await expect(page.locator('.gui-palette').getByRole('button', { name: 'Combobox — categoria' })).toBeVisible()
})
