import { expect, test } from '@playwright/test'

async function openStudio(page: import('@playwright/test').Page) {
  await page.goto('/ide')
  const start = page.getByRole('button', { name: 'Comenzar', exact: true })
  if (await start.isVisible()) await start.click()
  await expect(page.getByText('Python listo', { exact: true })).toBeVisible({ timeout: 100000 })
  await expect(page.locator('.monaco-editor')).toBeVisible({ timeout: 45000 })
}

test('themes, special styles and explorer presentation apply without changing files', async ({ page }) => {
  await openStudio(page)
  const original = await page.locator('.ide-toolbar').evaluate((node) => getComputedStyle(node).backgroundColor)
  await page.getByRole('button', { name: 'Configuración' }).click()
  await page.getByRole('button', { name: 'Rosa', exact: true }).click()
  await expect(page.locator('.coa-ide')).toHaveAttribute('data-accent', 'pink')
  await expect.poll(() => page.locator('.ide-toolbar').evaluate((node) => getComputedStyle(node).backgroundColor)).not.toBe(original)
  const pinkSurfaces = await page.locator('.coa-ide').evaluate(() => ['.ide-toolbar','.ide-activity','.ide-sidebar','.ide-tabs','.ide-console','.ide-status'].map((selector) => getComputedStyle(document.querySelector(selector)!).backgroundColor))
  expect(new Set(pinkSurfaces).size).toBeGreaterThan(3)
  await page.getByLabel('Color personalizado').fill('#2255aa')
  await expect(page.locator('.coa-ide')).toHaveAttribute('data-accent', 'custom')
  for (const style of ['vscode','eclipse','onlinegdb','python','cmd']) {
    await page.getByLabel('Estilo especial').selectOption(style)
    await expect(page.locator('.coa-ide')).toHaveClass(new RegExp(`theme-${style}`))
  }
  await page.getByLabel('Estilo especial').selectOption('eclipse')
  await page.getByRole('button', { name: 'Archivos', exact: true }).click()
  await expect(page.getByText('PACKAGE EXPLORER', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'main.py', exact: true })).toBeVisible()
})

test('background controls, editor settings and profiles persist locally', async ({ page }) => {
  await openStudio(page)
  await page.getByRole('button', { name: 'Configuración' }).click()
  await page.getByRole('button', { name: /Fondos/ }).click()
  await page.getByRole('button', { name: 'Ciudad nocturna' }).click()
  await expect(page.locator('.coa-ide')).toHaveAttribute('data-background', 'city')
  await expect.poll(() => page.locator('.ide-background').evaluate((node) => getComputedStyle(node).backgroundImage)).not.toBe('none')
  await page.getByRole('button', { name: /Editor/ }).click()
  await page.getByLabel('Tamaño de fuente').fill('16')
  await page.getByRole('button', { name: /Perfiles/ }).click()
  await page.getByLabel('Nombre').fill('Mi Setup')
  await page.getByRole('button', { name: 'Guardar perfil' }).click()
  await expect(page.getByLabel('Nombre de Mi Setup')).toHaveValue('Mi Setup')
  await page.reload()
  await expect(page.locator('.coa-ide')).toHaveAttribute('data-background', 'city')
  await page.getByRole('button', { name: 'Configuración' }).click()
  await page.getByRole('button', { name: /Perfiles/ }).click()
  await expect(page.getByLabel('Nombre de Mi Setup')).toBeVisible()
})

test('mobile quick bar inserts pairs, navigates and can be customized', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await openStudio(page)
  await page.locator('.monaco-editor textarea').focus()
  await expect(page.getByLabel('Barra rápida de programación')).toBeVisible()
  await page.keyboard.press('Control+A'); await page.keyboard.press('Backspace')
  await page.getByLabel('Barra rápida de programación').getByRole('button', { name: '()', exact: true }).click()
  await page.keyboard.insertText('x')
  await expect.poll(() => page.locator('.monaco-editor textarea').inputValue()).toContain('(x)')
  await page.getByRole('button', { name: 'Configuración' }).click()
  await page.getByRole('button', { name: /Móvil/ }).click()
  await page.getByLabel('Agregar atajo').selectOption('print()')
  await expect(page.getByLabel('Quitar print()')).toBeVisible()
  await page.reload()
  await page.locator('.monaco-editor textarea').focus()
  await expect(page.getByLabel('Barra rápida de programación').getByRole('button', { name: 'print()', exact: true })).toBeVisible()
})

test('custom background stays local, validates files and reset preserves the project', async ({ page }) => {
  await openStudio(page)
  await page.getByRole('button', { name: 'Configuración' }).click()
  await page.getByRole('button', { name: /Fondos/ }).click()
  const upload = page.locator('input[type=file][accept*="image/png"]')
  await upload.setInputFiles({ name: 'fondo.png', mimeType: 'image/png', buffer: Buffer.from('89504e470d0a1a0a', 'hex') })
  await expect(page.locator('.coa-ide')).toHaveAttribute('data-background', 'custom')
  await expect(page.getByRole('img', { name: 'Vista previa del fondo personalizado' })).toBeVisible()
  await page.getByRole('button', { name: 'Aplicar fondo' }).click()
  await expect(page.getByText('Fondo aplicado correctamente')).toBeVisible()
  await page.reload()
  await expect(page.locator('.coa-ide')).toHaveAttribute('data-background', 'custom')
  await page.getByRole('button', { name: 'Configuración' }).click()
  await page.getByRole('button', { name: /Restablecer/ }).click()
  page.once('dialog', (dialog) => dialog.accept())
  await page.getByRole('button', { name: 'Restaurar configuración predeterminada' }).click()
  await expect(page.locator('.coa-ide')).toHaveAttribute('data-background', 'none')
  await expect(page.getByRole('tab', { name: /main.py/ })).toBeVisible()
})

test('every visible scene renders and animated scenes have a real animation layer', async ({ page }) => {
  await openStudio(page)
  await page.getByRole('button', { name: 'Configuración' }).click()
  await page.getByRole('button', { name: /Fondos/ }).click()
  for (const [label,id] of [['Bosque','forest'],['Atardecer','sunset'],['Espacio','space'],['Cyberpunk','cyberpunk'],['Ciudad nocturna','city']] as const) {
    await page.getByRole('button', { name: label }).click()
    await expect(page.locator('.coa-ide')).toHaveAttribute('data-background', id)
    await expect.poll(() => page.locator('.ide-background').evaluate((node) => getComputedStyle(node).backgroundImage)).not.toBe('none')
  }
  await page.getByRole('button', { name: 'Estrellas animadas' }).click()
  await expect.poll(() => page.locator('.ide-background').evaluate((node) => getComputedStyle(node, '::before').animationName)).toBe('coa-stars')
  await page.getByRole('button', { name: 'Lluvia animada' }).click()
  await expect.poll(() => page.locator('.ide-background').evaluate((node) => getComputedStyle(node, '::before').animationName)).toBe('coa-rain')
  await page.getByRole('button', { name: 'Ninguno' }).click()
  await expect(page.locator('.ide-background')).toHaveCount(0)
})

test('VS Code, Eclipse and OnlineGDB skins change structure while execution remains real', async ({ page }) => {
  await openStudio(page)
  await page.getByRole('button', { name: 'Configuración' }).click()
  await page.getByLabel('Estilo especial').selectOption('vscode')
  await expect.poll(() => page.locator('.ide-activity').evaluate((node) => getComputedStyle(node).width)).toBe('48px')
  await page.getByRole('button', { name: 'Rosa' }).click()
  await expect(page.locator('.coa-ide')).toHaveClass(/theme-vscode/)
  await expect(page.locator('.coa-ide')).toHaveAttribute('data-accent', 'pink')
  await page.getByLabel('Estilo especial').selectOption('eclipse')
  await expect.poll(() => page.locator('.ide-toolbar').evaluate((node) => getComputedStyle(node).color)).not.toBe('rgb(34, 34, 34)')
  await page.getByRole('button', { name: 'Archivos' }).click()
  await expect(page.getByText('PACKAGE EXPLORER')).toBeVisible()
  await page.getByRole('button', { name: 'Configuración' }).click()
  await page.getByLabel('Estilo especial').selectOption('onlinegdb')
  await expect.poll(() => page.locator('.ide-activity').evaluate((node) => getComputedStyle(node).width)).toBe('128px')
  await expect.poll(() => page.locator('.ide-console').evaluate((node) => getComputedStyle(node).backgroundColor)).toBe('rgb(255, 255, 255)')
  await page.getByRole('button', { name: 'Ejecutar' }).click()
  await expect(page.getByTestId('python-output')).toContainText('Hola mundo')
})

test('mobile keyboard reduction enters focus mode and can be dismissed', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.addInitScript(() => {
    const viewport = new EventTarget() as EventTarget & { height: number; width: number }
    viewport.height = 520; viewport.width = 390
    Object.defineProperty(window, 'visualViewport', { configurable: true, value: viewport })
  })
  await openStudio(page)
  await page.locator('.monaco-editor textarea').focus()
  await expect(page.locator('.coa-ide')).toHaveClass(/mobile-focus/)
  await expect(page.getByRole('button', { name: 'Salir de enfoque' })).toBeVisible()
  await page.getByRole('button', { name: 'Salir de enfoque' }).click()
  await expect(page.locator('.coa-ide')).not.toHaveClass(/mobile-focus/)
  await expect(page.getByRole('button', { name: 'Configuración' })).toBeVisible()
})

test('dark palettes and skins always register and apply a dark Monaco theme', async ({ page }) => {
  await openStudio(page)
  await page.getByRole('button', { name: 'Configuración' }).click()
  const editorBackground = () => page.locator('.monaco-editor-background').first().evaluate((node) => getComputedStyle(node).backgroundColor)
  for (const palette of ['Morado','Rosa','Verde','Rojo','Naranja','Azul','Monocromático']) {
    await page.getByRole('button', { name: palette, exact: true }).click()
    await expect.poll(editorBackground).not.toBe('rgb(255, 255, 255)')
    await expect.poll(editorBackground).not.toBe('rgba(0, 0, 0, 0)')
  }
  for (const skin of ['cmd','vscode','eclipse','onlinegdb','pixel']) {
    await page.getByLabel('Estilo especial').selectOption(skin)
    await expect.poll(editorBackground).not.toBe('rgb(255, 255, 255)')
    await expect(page.locator('.coa-ide')).toHaveClass(new RegExp(`theme-${skin}`))
  }
  await page.getByLabel('Estilo especial').selectOption('python')
  await expect.poll(editorBackground).toBe('rgb(255, 255, 255)')
})

test('wallpaper mode makes the whole workbench and Monaco translucent', async ({ page }) => {
  await openStudio(page)
  await page.getByRole('button', { name: 'Configuración' }).click()
  await page.getByRole('button', { name: /Fondos/ }).click()
  await page.getByRole('button', { name: 'Bosque' }).click()
  await expect(page.locator('.coa-ide')).toHaveAttribute('data-wallpaper', 'true')
  await expect(page.locator('.coa-ide')).toHaveClass(/coa-wallpaper-active/)
  await page.getByLabel('Visibilidad del fondo').fill('85')
  await page.getByLabel('Transparencia de la interfaz').fill('60')
  await expect.poll(() => page.locator('.coa-ide').evaluate((node) => getComputedStyle(node).getPropertyValue('--background-opacity').trim())).toBe('0.85')
  await expect.poll(() => page.locator('.coa-ide').evaluate((node) => getComputedStyle(node).getPropertyValue('--interface-solid').trim())).toBe('40%')
  await expect.poll(() => page.locator('.monaco-editor-background').first().evaluate((node) => getComputedStyle(node).backgroundColor)).toContain('rgba')
  await page.getByRole('button', { name: /Apariencia/ }).click()
  await page.getByRole('button', { name: 'Morado' }).click()
  await page.getByLabel('Estilo especial').selectOption('vscode')
  await expect(page.locator('.coa-ide')).toHaveClass(/theme-vscode/)
  await expect(page.locator('.coa-ide')).toHaveClass(/coa-wallpaper-active/)
})

test('Pixel Art is a complete retro skin and coexists with a forest wallpaper', async ({ page }) => {
  await openStudio(page)
  await page.getByRole('button', { name: 'Configuración' }).click()
  await page.getByLabel('Estilo especial').selectOption('pixel')
  await expect(page.locator('.coa-ide')).toHaveClass(/theme-pixel/)
  await expect.poll(() => page.locator('.ide-toolbar').evaluate((node) => getComputedStyle(node).borderBottomWidth)).toBe('3px')
  await expect.poll(() => page.locator('.ide-console').evaluate((node) => getComputedStyle(node).borderTopWidth)).toBe('4px')
  await expect.poll(() => page.locator('.ide-tab.active').evaluate((node) => getComputedStyle(node).borderRadius)).toBe('0px')
  await expect.poll(() => page.locator('.coa-ide').evaluate((node) => getComputedStyle(node).fontFamily)).toContain('Courier New')
  await page.getByRole('button', { name: /Fondos/ }).click()
  await page.getByRole('button', { name: 'Bosque' }).click()
  await expect(page.locator('.coa-ide')).toHaveClass(/coa-wallpaper-active/)
  await expect.poll(() => page.locator('.monaco-editor-background').first().evaluate((node) => getComputedStyle(node).backgroundColor)).toContain('rgba')
})

test('settings close button remains usable after changes and GIF is accepted locally', async ({ page }) => {
  await openStudio(page)
  await page.getByRole('button', { name: 'Configuración' }).click()
  await page.getByRole('button', { name: 'Rosa' }).click()
  await page.getByRole('button', { name: /Fondos/ }).click()
  const upload = page.locator('input[type=file][accept*="image/gif"]')
  await upload.setInputFiles({ name: 'animado.gif', mimeType: 'image/gif', buffer: Buffer.from('474946383961', 'hex') })
  await expect(page.locator('.coa-ide')).toHaveAttribute('data-background', 'custom')
  await expect(page.getByRole('img', { name: 'Vista previa del fondo personalizado' })).toBeVisible()
  await page.getByRole('button', { name: 'Cerrar panel' }).click()
  await expect(page.getByRole('heading', { name: 'Personaliza tu Studio' })).toBeHidden()
  await expect(page.locator('.monaco-editor')).toBeVisible()
})

test('CMD is black while OnlineGDB keeps cyan navigation, gray Monaco and white console', async ({ page }) => {
  await openStudio(page)
  await page.getByRole('button', { name: 'Configuración' }).click()
  await page.getByLabel('Estilo especial').selectOption('cmd')
  for (const selector of ['.ide-toolbar','.ide-activity','.ide-sidebar','.ide-tabs','.ide-console','.ide-status','.monaco-editor-background']) {
    await expect.poll(() => page.locator(selector).first().evaluate((node) => getComputedStyle(node).backgroundColor)).toBe('rgb(0, 0, 0)')
  }
  await page.getByLabel('Estilo especial').selectOption('onlinegdb')
  await expect.poll(() => page.locator('.ide-activity').evaluate((node) => getComputedStyle(node).backgroundColor)).toBe('rgb(37, 169, 224)')
  await expect.poll(() => page.locator('.monaco-editor-background').first().evaluate((node) => getComputedStyle(node).backgroundColor)).toBe('rgb(43, 45, 49)')
  await expect.poll(() => page.locator('.ide-console').evaluate((node) => getComputedStyle(node).backgroundColor)).toBe('rgb(255, 255, 255)')
})
