// Contenido reservado para una futura implementación posterior a la evaluación.
// No se importa en la página del estudiante para mantener ocultas las respuestas.
export const logicaModulo1Soluciones = {
  ejercicios: [
    {
      titulo: 'Solución del ejercicio 1',
      contenido: [
        '1. “La aplicación es muy mala.”',
        'Es un síntoma o una opinión general.',
        'Preguntas posibles: ¿qué tarea no pudo completar la persona?, ¿qué ocurrió exactamente?',
        '2. “Durante tres compras de prueba, el total mostrado fue diferente de la suma de los productos.”',
        'Describe un problema bastante concreto. Aun así, sería necesario registrar los productos, precios y resultados.',
        '3. “Los estudiantes no entienden el curso.”',
        'Es un síntoma general.',
        'Preguntas posibles: ¿qué tema no entienden?, ¿en qué actividad aparecen los errores?',
        '4. “Cinco estudiantes indicaron que no encontraron el botón para continuar a la siguiente lección.”',
        'Es un problema más específico y comprobable.',
      ],
    },
    {
      titulo: 'Solución del ejercicio 2',
      contenido: [
        'Hechos',
        'Se prepararon 40 almuerzos.',
        'A la 1:00 p. m. quedaban 25.',
        'Por lo tanto, hasta esa hora se habían vendido 15, si no hubo pérdidas o retiros.',
        'Suposición',
        'Que el precio fue la causa de las ventas bajas.',
        'Información que podría investigarse',
        'precio comparado con cafeterías cercanas;',
        'cantidad habitual de clientes;',
        'horario de mayor demanda;',
        'calidad o variedad del menú;',
        'visibilidad de la cafetería;',
        'existencia de un evento que redujera la asistencia.',
        'Otra causa posible',
        'Ese día acudieron menos clientes de lo habitual.',
      ],
    },
    {
      titulo: 'Solución posible del ejercicio 3',
      contenido: [
        '1. Separar las prendas que no deben lavarse juntas.',
        '2. Colocar la ropa seleccionada dentro.',
        '3. Agregar el detergente.',
        '4. Cerrar la puerta.',
        '5. Seleccionar el ciclo apropiado.',
        '6. Iniciar el ciclo.',
        '7. Retirar la ropa cuando termine.',
        'Dependencias:',
        'la ropa debe colocarse antes de iniciar;',
        'la puerta debe cerrarse antes de iniciar;',
        'la ropa solo debe retirarse después de terminar.',
        'Ambigüedad:',
        '“Agregar el detergente.”',
        'Versión más precisa:',
        'Colocar la cantidad de detergente indicada para el volumen de ropa en el compartimento correspondiente.',
      ],
    },
    {
      titulo: 'Solución posible del ejercicio 4',
      contenido: [
        'Dudas del robot:',
        '¿qué hoja debe tomar?;',
        '¿cómo debe elegirla?;',
        '¿en qué dirección debe doblarla?;',
        '¿cuántas veces debe doblarla?;',
        '¿en cuál caja debe colocarla?;',
        '¿en qué posición debe dejarla?',
        'Versión mejorada:',
        '1. Localiza la hoja azul.',
        '2. Toma la hoja azul.',
        '3. Colócala horizontalmente sobre el centro de la mesa.',
        '4. Lleva el borde izquierdo hasta hacerlo coincidir con el borde derecho.',
        '5. Presiona el doblez.',
        '6. Toma la hoja doblada.',
        '7. Colócala dentro de la caja marcada con la letra A.',
        '8. Suelta la hoja.',
      ],
    },
    {
      titulo: 'Solución posible del ejercicio 5',
      contenido: [
        'A. Pintura para una pared',
        'Entradas: alto, ancho y rendimiento de la pintura.',
        'Proceso: calcular el área y relacionarla con el rendimiento por litro.',
        'Salida: litros aproximados necesarios.',
        'B. Costo de un viaje',
        'Entradas: distancia, consumo del vehículo, precio del combustible y posibles peajes.',
        'Proceso: calcular combustible requerido, costo del combustible y sumar peajes.',
        'Salida: costo aproximado.',
        'C. Finalización de una película',
        'Entradas: hora de inicio y duración.',
        'Proceso: sumar la duración a la hora de inicio.',
        'Salida: hora aproximada de finalización.',
      ],
    },
    {
      titulo: 'Solución posible del ejercicio 6',
      contenido: [
        'ENTREGAR PEDIDO',
        '├── Recibir la información del pedido',
        '├── Preparar los productos',
        '├── Empacar',
        '├── Identificar el destino',
        '├── Transportar',
        '├── Entregar',
        '└── Confirmar la entrega',
        'Descomposición de “Empacar”:',
        'EMPACAR',
        '├── Comprobar los productos',
        '├── Elegir el recipiente apropiado',
        '├── Colocar los productos',
        '├── Proteger los artículos delicados',
        '└── Cerrar e identificar el paquete',
        'Pueden existir otras divisiones correctas.',
      ],
    },
    {
      titulo: 'Solución posible del ejercicio 7',
      contenido: [
        'Lista',
        '1. Localizar la botella sobre la mesa.',
        '2. Tomar la botella.',
        '3. Moverse hasta el destinatario.',
        '4. Extender la botella hacia el destinatario.',
        '5. Esperar a que la sujete.',
        '6. Soltarla.',
        'Pseudocódigo',
        'INICIO',
        'LOCALIZAR la botella sobre la mesa',
        'TOMAR la botella',
        'MOVERSE hasta el destinatario',
        'EXTENDER la botella',
        'ESPERAR hasta que el destinatario la sujete',
        'SOLTAR la botella',
        'FIN',
        'Flujo',
        'INICIO',
        '↓',
        'Localizar botella',
        '↓',
        'Tomar botella',
        '↓',
        'Moverse hasta el destinatario',
        '↓',
        'Entregar botella',
        '↓',
        'FIN',
      ],
    },
  ],
  retos: [
    {
      titulo: 'Solución posible del reto 1',
      contenido: [
        'Posibles fallos:',
        'se imprime una versión incorrecta;',
        'faltan páginas;',
        'las páginas están desordenadas;',
        'se utiliza un sobre inadecuado;',
        'no se escribe la dirección;',
        'se escribe una dirección desactualizada;',
        'el sobre no se cierra;',
        'no se utiliza el servicio de envío correcto;',
        'no se conserva una confirmación.',
        'Una solución mejor debe agregar comprobaciones concretas, pero no describir detalles irrelevantes como cada movimiento de los dedos.',
      ],
    },
    {
      titulo: 'Solución posible del reto 2',
      contenido: [
        '1. El algoritmo B es más preciso.',
        '2. El algoritmo A es más breve.',
        '3. No. Ser breve no ayuda si las instrucciones quedan incompletas.',
        '4. Podría funcionar para una persona que comprende el contexto y sabe dónde guardar los objetos.',
        '5. Los pasos 2–6 describen una idea repetida.',
        '6. Una versión equilibrada podría ser:',
        '1. Localiza la caja.',
        '2. Recorre los objetos de izquierda a derecha.',
        '3. Toma un objeto a la vez.',
        '4. Coloca cada objeto dentro de la caja.',
        '5. Comprueba que los cinco objetos estén dentro.',
        '6. Comprueba que la mesa esté vacía.',
        'La repetición se formalizará en el Módulo 4.',
      ],
    },
  ],
  evaluacion: [
    ['Pregunta 1', 'B', 'Un algoritmo es una secuencia de pasos.'],
    ['Pregunta 2', 'C', '“Correctamente” no define un resultado preciso.'],
    ['Pregunta 3', 'C', 'Sin el precio no puede calcularse el costo.'],
    ['Pregunta 4', 'D', 'El total es el resultado producido.'],
    ['Pregunta 5', 'C', 'Descomponer permite trabajar con partes manejables.'],
    ['Pregunta 6', 'B', 'El rectángulo representa una acción o proceso.'],
    ['Pregunta 7', 'C', 'El algoritmo es independiente del lenguaje.'],
    ['Pregunta 8', 'B', 'La simulación permite localizar el primer paso incorrecto.'],
  ],
}
