-- Fase 3: demanda de cursos, proyectos moderados y perfil público mínimo.
alter table public.profiles add column public_slug text unique, add column public_bio text, add column occupation text, add column public_location text, add column public_github_url text, add column avatar_path text;
alter table public.profiles add constraint profiles_public_slug_format check(public_slug is null or public_slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'), add constraint profiles_public_bio_length check(public_bio is null or char_length(public_bio)<=500), add constraint profiles_occupation_length check(occupation is null or char_length(occupation)<=120), add constraint profiles_public_location_length check(public_location is null or char_length(public_location)<=120);

create table public.course_proposals(
 id uuid primary key default gen_random_uuid(), slug text not null unique check(slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'), name text not null check(char_length(trim(name)) between 2 and 160), short_description text not null check(char_length(trim(short_description)) between 2 and 300), content text not null check(char_length(trim(content)) between 2 and 10000), image_path text, price_text text not null, modality text not null, duration text not null, schedule_text text not null, minimum_requests integer not null check(minimum_requests between 1 and 10000), status text not null default 'draft' check(status in('draft','open','closed','archived')), display_order integer not null default 100, created_by uuid not null references public.profiles(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table public.course_proposal_options(
 id uuid primary key default gen_random_uuid(), proposal_id uuid not null references public.course_proposals(id) on delete cascade, weekday smallint check(weekday between 0 and 6), proposed_start_date date, label text, display_order integer not null default 1, created_at timestamptz not null default now(), check(weekday is not null or proposed_start_date is not null or nullif(trim(label),'') is not null)
);
create table public.course_requests(
 proposal_id uuid not null references public.course_proposals(id) on delete cascade, user_id uuid not null references public.profiles(id) on delete cascade, option_id uuid not null references public.course_proposal_options(id) on delete restrict, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), primary key(proposal_id,user_id)
);
create index course_proposals_public_idx on public.course_proposals(status,display_order,created_at desc);create index course_requests_option_idx on public.course_requests(proposal_id,option_id);
create view public.course_proposal_demand with(security_invoker=false) as select p.id proposal_id,count(r.user_id)::integer total_requests from public.course_proposals p left join public.course_requests r on r.proposal_id=p.id group by p.id;
revoke all on public.course_proposal_demand from public;grant select on public.course_proposal_demand to anon,authenticated;

create table public.student_projects(
 id uuid primary key default gen_random_uuid(), slug text not null unique check(slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'), author_id uuid not null references public.profiles(id) on delete cascade, course_id uuid references public.courses(id) on delete set null, title text not null check(char_length(trim(title)) between 2 and 160), description text not null check(char_length(trim(description)) between 10 and 5000), technologies text[] not null default '{}', youtube_id text check(youtube_id is null or youtube_id ~ '^[A-Za-z0-9_-]{11}$'), github_url text, status text not null default 'pending' check(status in('draft','pending','published','rejected')), rejection_reason text, moderated_by uuid references public.profiles(id), moderated_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table public.student_project_images(id uuid primary key default gen_random_uuid(),project_id uuid not null references public.student_projects(id) on delete cascade,storage_path text not null unique,alt_text text,display_order smallint not null check(display_order between 1 and 5),created_at timestamptz not null default now(),unique(project_id,display_order));
create index student_projects_public_idx on public.student_projects(status,created_at desc);create index student_projects_author_idx on public.student_projects(author_id,status,created_at desc);

create view public.public_profiles with(security_invoker=false) as select id,coalesce(public_slug,id::text) slug,full_name,public_bio,occupation,public_location,public_github_url,avatar_path from public.profiles;
revoke all on public.public_profiles from public;grant select on public.public_profiles to anon,authenticated;

alter table public.course_proposals enable row level security;alter table public.course_proposal_options enable row level security;alter table public.course_requests enable row level security;alter table public.student_projects enable row level security;alter table public.student_project_images enable row level security;
create policy proposals_public_read on public.course_proposals for select to anon,authenticated using(status='open' or (select public.is_admin()));create policy proposals_admin_manage on public.course_proposals for all to authenticated using((select public.is_admin())) with check((select public.is_admin()));
create policy proposal_options_public_read on public.course_proposal_options for select to anon,authenticated using(exists(select 1 from public.course_proposals p where p.id=proposal_id and (p.status='open' or (select public.is_admin()))));create policy proposal_options_admin_manage on public.course_proposal_options for all to authenticated using((select public.is_admin())) with check((select public.is_admin()));
create policy requests_own_or_admin_read on public.course_requests for select to authenticated using(user_id=(select auth.uid()) or (select public.is_admin()));create policy requests_admin_delete on public.course_requests for delete to authenticated using((select public.is_admin()));
create policy projects_visible on public.student_projects for select to anon,authenticated using(status='published' or author_id=(select auth.uid()) or (select public.is_admin()));create policy projects_author_insert on public.student_projects for insert to authenticated with check(author_id=(select auth.uid()) and status in('draft','pending') and moderated_by is null);create policy projects_author_update on public.student_projects for update to authenticated using(author_id=(select auth.uid()) and status in('draft','pending','rejected')) with check(author_id=(select auth.uid()) and status in('draft','pending') and moderated_by is null);create policy projects_author_delete on public.student_projects for delete to authenticated using(author_id=(select auth.uid()) or (select public.is_admin()));
create policy project_images_visible on public.student_project_images for select to anon,authenticated using(exists(select 1 from public.student_projects p where p.id=project_id and(p.status='published' or p.author_id=(select auth.uid()) or (select public.is_admin()))));create policy project_images_owner_insert on public.student_project_images for insert to authenticated with check(exists(select 1 from public.student_projects p where p.id=project_id and p.author_id=(select auth.uid()) and p.status in('draft','pending')));create policy project_images_owner_delete on public.student_project_images for delete to authenticated using(exists(select 1 from public.student_projects p where p.id=project_id and(p.author_id=(select auth.uid()) or (select public.is_admin()))));

revoke all on public.course_proposals,public.course_proposal_options,public.course_requests,public.student_projects,public.student_project_images from anon,authenticated;grant select on public.course_proposals,public.course_proposal_options,public.student_projects,public.student_project_images to anon,authenticated;grant select on public.course_requests to authenticated;grant insert,update,delete on public.course_proposals,public.course_proposal_options to authenticated;grant delete on public.course_requests to authenticated;grant insert(author_id,slug,course_id,title,description,technologies,youtube_id,github_url,status),update(course_id,title,description,technologies,youtube_id,github_url,status,rejection_reason),delete on public.student_projects to authenticated;grant insert(project_id,storage_path,alt_text,display_order),delete on public.student_project_images to authenticated;
grant update(public_slug,public_bio,occupation,public_location,public_github_url,avatar_path) on public.profiles to authenticated;

create or replace function public.set_course_request(p_proposal uuid,p_option uuid) returns void language plpgsql security definer set search_path='' as $$ begin if auth.uid() is null then raise exception 'authentication required';end if;if not exists(select 1 from public.course_proposal_options o join public.course_proposals p on p.id=o.proposal_id where o.id=p_option and o.proposal_id=p_proposal and p.status='open') then raise exception 'proposal unavailable';end if;insert into public.course_requests(proposal_id,user_id,option_id) values(p_proposal,auth.uid(),p_option) on conflict(proposal_id,user_id) do update set option_id=excluded.option_id,updated_at=now();end $$;
create or replace function public.withdraw_course_request(p_proposal uuid) returns void language sql security definer set search_path='' as $$delete from public.course_requests where proposal_id=p_proposal and user_id=auth.uid()$$;
create or replace function public.moderate_student_project(p_project uuid,p_status text,p_reason text default null) returns void language plpgsql security definer set search_path='' as $$begin if not public.is_admin() then raise exception 'admin required';end if;if p_status not in('published','rejected','pending') then raise exception 'invalid status';end if;update public.student_projects set status=p_status,rejection_reason=case when p_status='rejected' then nullif(trim(p_reason),'') else null end,moderated_by=auth.uid(),moderated_at=now(),updated_at=now() where id=p_project;if not found then raise exception 'project unavailable';end if;end$$;
revoke all on function public.set_course_request(uuid,uuid),public.withdraw_course_request(uuid),public.moderate_student_project(uuid,text,text) from public,anon;grant execute on function public.set_course_request(uuid,uuid),public.withdraw_course_request(uuid) to authenticated;grant execute on function public.moderate_student_project(uuid,text,text) to authenticated;

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('phase3-media','phase3-media',false,5242880,array['image/png','image/jpeg','image/webp']) on conflict(id) do update set public=false,file_size_limit=5242880,allowed_mime_types=excluded.allowed_mime_types;
create policy phase3_media_insert on storage.objects for insert to authenticated with check(bucket_id='phase3-media' and array_length(storage.foldername(name),1)=2 and(((storage.foldername(name))[1]=auth.uid()::text and exists(select 1 from public.student_projects p where p.id::text=(storage.foldername(name))[2] and p.author_id=auth.uid())) or ((storage.foldername(name))[1]='proposals' and public.is_admin())));
create policy phase3_media_read on storage.objects for select to anon,authenticated using(bucket_id='phase3-media' and(exists(select 1 from public.student_project_images i join public.student_projects p on p.id=i.project_id where i.storage_path=name and(p.status='published' or p.author_id=auth.uid() or public.is_admin())) or ((storage.foldername(name))[1]='proposals' and exists(select 1 from public.course_proposals p where p.image_path=name and(p.status='open' or public.is_admin())))));
create policy phase3_media_delete on storage.objects for delete to authenticated using(bucket_id='phase3-media' and((storage.foldername(name))[1]=auth.uid()::text or public.is_admin()));
create trigger course_proposals_updated before update on public.course_proposals for each row execute procedure public.set_profile_updated_at();create trigger student_projects_updated before update on public.student_projects for each row execute procedure public.set_profile_updated_at();
