import Link from 'next/link'
import { Bookmark, BookOpen, Compass, FolderKanban, Layers3, Search, UsersRound } from 'lucide-react'

type Item={label:string;count:number;href:string;active?:boolean}
const navClass=(active:boolean)=>`flex items-center gap-3 rounded-xl px-3 py-2 text-sm font-semibold ${active?'bg-primary/10 text-primary':'hover:bg-secondary'}`

export function ProjectCommunityLeft({categories,courses,savedHref,showAllCourses}:{categories:Item[];courses:Item[];savedHref:string;showAllCourses:boolean}){return <aside className="space-y-5"><nav className="rounded-2xl border bg-card p-3 shadow-sm"><Link href="/proyectos" className={navClass(true)}><FolderKanban className="h-5 w-5"/>Proyectos COA</Link><Link href="/proyectos" className={navClass(false)}><Compass className="h-5 w-5"/>Explorar</Link><Link href="/mi-coa/proyectos" className={navClass(false)}><BookOpen className="h-5 w-5"/>Mis proyectos</Link><Link href={savedHref} className={navClass(false)}><Bookmark className="h-5 w-5"/>Guardados</Link></nav><section className="rounded-2xl border bg-card p-4 shadow-sm"><h2 className="text-sm font-extrabold uppercase tracking-wide">Categorías</h2><div className="mt-3 space-y-1">{categories.map(item=><Link key={item.label} href={item.href} className={`${navClass(!!item.active)} justify-between`}><span>{item.label}</span><span className="rounded-full bg-background px-2 py-0.5 text-xs">{item.count}</span></Link>)}</div></section><section className="rounded-2xl border bg-card p-4 shadow-sm"><h2 className="text-sm font-extrabold uppercase tracking-wide">Cursos relacionados</h2><div className="mt-3 space-y-1">{courses.map(item=><Link key={item.label} href={item.href} className={`${navClass(!!item.active)} justify-between`}><span className="truncate">{item.label}</span><span className="rounded-full bg-secondary px-2 py-0.5 text-xs">{item.count}</span></Link>)}</div>{showAllCourses&&<Link href="/proyectos" className="mt-4 inline-flex text-sm font-bold text-primary">Ver todos los cursos →</Link>}</section></aside>}

export function ProjectCommunityRight({stats,technologies,recent,allTechnologiesHref}:{stats:Array<{label:string;value:number}>;technologies:Item[];recent:Array<{title:string;author:string;href:string}>;allTechnologiesHref?:string}){return <aside className="space-y-5"><section className="rounded-2xl border bg-card p-4 shadow-sm"><h2 className="font-extrabold">Estadísticas de la comunidad</h2><div className="mt-4 grid grid-cols-2 gap-2">{stats.map(item=><div key={item.label} className="rounded-xl bg-secondary/70 p-3"><p className="text-xl font-extrabold text-primary">{item.value}</p><p className="mt-1 text-xs text-muted-foreground">{item.label}</p></div>)}</div></section><section className="rounded-2xl border bg-card p-4 shadow-sm"><h2 className="font-extrabold">Tecnologías populares</h2><div className="mt-3 space-y-2">{technologies.map(item=><Link key={item.label} href={item.href} className="flex items-center justify-between rounded-lg bg-secondary/60 px-3 py-2 text-sm hover:bg-secondary"><span>{item.label}</span><span className="rounded-full bg-background px-2 py-0.5 text-xs">{item.count}</span></Link>)}</div>{technologies.length===0&&<p className="mt-3 text-sm text-muted-foreground">Aún no hay tecnologías registradas.</p>}{allTechnologiesHref&&<Link href={allTechnologiesHref} className="mt-4 inline-flex text-sm font-bold text-primary">Ver todas las tecnologías →</Link>}</section>{recent.length>0&&<section className="rounded-2xl border bg-card p-4 shadow-sm"><div className="flex items-center gap-2"><Layers3 className="h-5 w-5 text-primary"/><h2 className="font-extrabold">Proyectos recientes</h2></div><div className="mt-3 space-y-3">{recent.map(item=><Link key={item.href} href={item.href} className="block rounded-lg p-2 hover:bg-secondary"><b className="block text-sm">{item.title}</b><span className="text-xs text-muted-foreground">{item.author}</span></Link>)}</div></section>}<section className="rounded-2xl bg-primary/10 p-4"><div className="flex gap-3"><UsersRound className="h-8 w-8 shrink-0 text-primary"/><p className="text-sm text-muted-foreground"><b className="block text-foreground">Únete a la comunidad</b>Comparte tus proyectos, conoce el trabajo de otros estudiantes y sigue aprendiendo.</p></div></section></aside>}

export function CommunitySearch(){return <div className="flex items-center gap-2 rounded-xl border bg-card px-3 py-2"><Search className="h-4 w-4 text-muted-foreground"/><input name="q" aria-label="Buscar proyectos" placeholder="Buscar proyectos..." className="min-w-0 flex-1 bg-transparent text-sm outline-none"/><button className="sr-only">Buscar</button></div>}
