'use client'

import Image from 'next/image'
import Link from 'next/link'
import { Bookmark, Check, Copy, ExternalLink, MoreVertical, Plus, X } from 'lucide-react'
import { useEffect, useState, useTransition } from 'react'
import { useRouter } from 'next/navigation'
import { toggleProjectSave } from '@/app/phase3-actions'

export type CommunityFeedProject={id:string;slug:string;title:string;description:string;technologies:string[];githubUrl:string|null;youtubeId:string|null;createdAt:string;author:{name:string;slug:string;avatarUrl:string|null};courseTitle:string|null;images:Array<{url:string;alt:string}>}
const formatDate=(value:string)=>new Intl.DateTimeFormat('es-CR',{dateStyle:'long'}).format(new Date(value))
const initials=(name:string)=>name.trim().split(/\s+/).slice(0,2).map(part=>part[0]).join('').toUpperCase()||'CO'

function Gallery({project}:{project:CommunityFeedProject}){
 const[open,setOpen]=useState(false),images=project.images,visible=images.slice(0,3),extra=images.length-visible.length
 useEffect(()=>{if(!open)return;const close=(event:KeyboardEvent)=>{if(event.key==='Escape')setOpen(false)};document.addEventListener('keydown',close);return()=>document.removeEventListener('keydown',close)},[open])
 if(!images.length)return null
 return <><div className={`mt-5 grid gap-1 overflow-hidden rounded-2xl border bg-secondary ${images.length===1?'grid-cols-1':images.length===2?'grid-cols-2':'grid-cols-[minmax(0,2fr)_minmax(130px,1fr)]'}`}>
  <button type="button" onClick={()=>setOpen(true)} className={`relative min-h-52 overflow-hidden text-left focus:outline-none focus:ring-2 focus:ring-primary ${images.length>2?'row-span-2':''}`} aria-label="Ver todas las imágenes del proyecto"><Image fill src={images[0].url} alt={images[0].alt} sizes="(max-width: 768px) 100vw, 640px" className="object-contain bg-secondary"/></button>
  {visible.slice(1).map((image,index)=><button type="button" key={image.url} onClick={()=>setOpen(true)} className="relative min-h-24 overflow-hidden text-left focus:outline-none focus:ring-2 focus:ring-primary" aria-label="Ver todas las imágenes del proyecto"><Image fill src={image.url} alt={image.alt} sizes="(max-width: 768px) 50vw, 240px" className="object-contain bg-secondary"/>{index===visible.length-2&&extra>0&&<span className="absolute inset-0 grid place-items-center bg-foreground/70 text-center text-sm font-bold text-background">+{extra}<br/>Ver todas</span>}</button>)}
 </div>
 {open&&<div role="dialog" aria-modal="true" aria-label={`Imágenes de ${project.title}`} className="fixed inset-0 z-50 grid place-items-center bg-black/80 p-4" onClick={()=>setOpen(false)}><div className="relative max-h-full w-full max-w-5xl overflow-y-auto rounded-2xl bg-background p-4" onClick={event=>event.stopPropagation()}><button type="button" onClick={()=>setOpen(false)} aria-label="Cerrar imágenes" className="absolute right-6 top-6 z-10 grid h-10 w-10 place-items-center rounded-full bg-background/90 shadow"><X className="h-5 w-5"/></button><div className="grid gap-4">{images.map(image=><div key={image.url} className="relative aspect-video"><Image fill src={image.url} alt={image.alt} sizes="(max-width: 1024px) 100vw, 1000px" className="object-contain"/></div>)}</div></div></div>}
 </>
}

function ProjectMenu({project,saved,canSave,onSaved}:{project:CommunityFeedProject;saved:boolean;canSave:boolean;onSaved:(saved:boolean)=>void}){
 const[open,setOpen]=useState(false),[copied,setCopied]=useState(false),[pending,startTransition]=useTransition(),router=useRouter()
 const copy=async()=>{const url=`${window.location.origin}/proyectos/${project.slug}`;try{await navigator.clipboard.writeText(url)}catch{const input=document.createElement('textarea');input.value=url;input.style.position='fixed';input.style.opacity='0';document.body.append(input);input.select();document.execCommand('copy');input.remove()}setCopied(true);setTimeout(()=>setCopied(false),1800);setOpen(false)}
 const save=()=>{if(!canSave){router.push(`/cuenta/iniciar-sesion?next=${encodeURIComponent('/proyectos')}`);return}startTransition(async()=>{const result=await toggleProjectSave(project.id);if(typeof result?.saved==='boolean')onSaved(result.saved);setOpen(false)})}
 return <div className="relative"><button type="button" onClick={()=>setOpen(value=>!value)} aria-label={`Más acciones para ${project.title}`} aria-expanded={open} className="grid h-9 w-9 place-items-center rounded-full text-muted-foreground hover:bg-secondary"><MoreVertical className="h-5 w-5"/></button>{open&&<div className="absolute right-0 z-20 mt-1 w-56 rounded-xl border bg-background p-1 shadow-lg"><button type="button" disabled={pending} onClick={save} className="flex w-full items-center gap-2 rounded-lg px-3 py-2 text-left text-sm hover:bg-secondary"><Bookmark className="h-4 w-4"/>{saved?'Quitar de guardados':'Guardar proyecto'}</button><button type="button" onClick={copy} className="flex w-full items-center gap-2 rounded-lg px-3 py-2 text-left text-sm hover:bg-secondary">{copied?<Check className="h-4 w-4"/>:<Copy className="h-4 w-4"/>}{copied?'Enlace copiado':'Copiar enlace'}</button><Link href={`/autores/${project.author.slug}`} onClick={()=>setOpen(false)} className="flex items-center gap-2 rounded-lg px-3 py-2 text-sm hover:bg-secondary">Ver perfil del autor</Link></div>}</div>
}

function CommunityPost({project,canSave,initialSaved}:{project:CommunityFeedProject;canSave:boolean;initialSaved:boolean}){
 const[expanded,setExpanded]=useState(false),[saved,setSaved]=useState(initialSaved),long=project.description.length>300
 return <article className="rounded-2xl border bg-card p-5 shadow-sm sm:p-6"><header className="flex gap-3"><Link href={`/autores/${project.author.slug}`} className="shrink-0">{project.author.avatarUrl?<Image src={project.author.avatarUrl} alt={`Perfil de ${project.author.name}`} width={44} height={44} unoptimized className="h-11 w-11 rounded-full object-cover"/>:<span aria-label={`Iniciales de ${project.author.name}`} className="grid h-11 w-11 place-items-center rounded-full bg-primary text-sm font-extrabold text-primary-foreground">{initials(project.author.name)}</span>}</Link><div className="min-w-0 flex-1"><Link href={`/autores/${project.author.slug}`} className="font-bold hover:text-primary">{project.author.name}</Link><p className="truncate text-sm text-muted-foreground">{project.courseTitle?`${project.courseTitle} · `:''}{formatDate(project.createdAt)}</p></div><ProjectMenu project={project} saved={saved} canSave={canSave} onSaved={setSaved}/></header><h2 className="mt-4 text-xl font-extrabold sm:text-2xl">{project.title}</h2><p className={`mt-3 whitespace-pre-wrap leading-relaxed text-muted-foreground ${!expanded&&long?'line-clamp-4':''}`}>{project.description}</p>{long&&<button type="button" onClick={()=>setExpanded(value=>!value)} className="mt-1 text-sm font-bold text-primary">{expanded?'Ver menos':'Ver más'}</button>}<Gallery project={project}/>{!!project.technologies.length&&<div className="mt-5 flex flex-wrap gap-2">{project.technologies.map(technology=><span key={technology} className="rounded-full bg-secondary px-3 py-1 text-sm">{technology}</span>)}</div>}<footer className="mt-5 flex flex-wrap justify-end gap-3">{project.githubUrl&&<a href={project.githubUrl} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-1 rounded-xl border px-4 py-2 text-sm font-bold">GitHub <ExternalLink className="h-4 w-4"/></a>}<Link href={`/proyectos/${project.slug}`} className="inline-flex items-center gap-2 rounded-xl bg-primary px-4 py-2 text-sm font-bold text-primary-foreground">Ver proyecto <Plus className="h-4 w-4"/></Link></footer></article>
}

export function ProjectCommunityFeed({projects,canSave,savedIds,empty}:{projects:CommunityFeedProject[];canSave:boolean;savedIds:string[];empty:string}){return !projects.length?<p className="rounded-2xl border bg-card p-8 text-center text-muted-foreground">{empty}</p>:<div className="space-y-5">{projects.map(project=><CommunityPost key={project.id} project={project} canSave={canSave} initialSaved={savedIds.includes(project.id)}/>)}</div>}
