'use server'
import{randomUUID}from'node:crypto'
import{revalidatePath}from'next/cache'
import{redirect}from'next/navigation'
import{requireAdmin}from'@/lib/auth/session'
import{costaRicaDeadline,isSafeAcademicFilename,liveGroupSlug}from'@/lib/live-groups'
import{createClient}from'@/lib/supabase/server'
import{logSupabaseError}from'@/lib/supabase-error-log'
const field=(data:FormData,key:string)=>String(data.get(key)??'').trim()
const refresh=(id?:string)=>{revalidatePath('/admin/grupos');revalidatePath('/');if(id)revalidatePath(`/admin/grupos/${id}`)}
export async function createGroup(data:FormData){const{user}=await requireAdmin(),supabase=await createClient(),name=field(data,'name'),courseId=field(data,'course_id'),base=liveGroupSlug(name);if(!name||!courseId)return;const{data:group,error}=await supabase.from('live_groups').insert({course_id:courseId,name,slug:`${base}-${randomUUID().slice(0,6)}`,starts_on:field(data,'starts_on')||null,status:field(data,'status')||'preparation',created_by:user.id}).select('id').single();if(error||!group)throw new Error('No pudimos crear el grupo.');refresh();redirect(`/admin/grupos/${group.id}`)}
export async function updateGroup(data:FormData){const{user}=await requireAdmin();const supabase=await createClient(),id=field(data,'group_id'),file=data.get('image') as File|null;const{data:current,error:groupError}=await supabase.from('live_groups').select('image_path').eq('id',id).single<{image_path:string|null}>();if(groupError){logSupabaseError('read-cover-group',groupError,{groupId:id,userId:user.id});throw new Error('No pudimos consultar el grupo.')}const values:{name:string;status:string;starts_on:string|null;image_path?:string}={name:field(data,'name'),status:field(data,'status'),starts_on:field(data,'starts_on')||null};let newPath:string|null=null;if(file&&file.size){if(!['image/png','image/jpeg','image/webp','image/gif'].includes(file.type)||file.size>5*1024*1024)throw new Error('La portada debe ser PNG, JPG, WEBP o GIF y pesar hasta 5 MB.');newPath=`${id}/covers/${randomUUID()}`;const{data:isAdmin,error:adminError}=await supabase.rpc('is_admin');if(adminError||isAdmin!==true){logSupabaseError('upload-cover-admin-check',adminError,{groupId:id,userId:user.id,isAdmin});throw new Error('La sesión actual no tiene permisos administrativos para subir la portada.')}const context={bucket:'live-group-assets',path:newPath,folders:[id,'covers'],folderCount:2,mimeType:file.type,sizeBytes:file.size,maxSizeBytes:5*1024*1024,groupId:id,groupExists:true,userId:user.id,isAdmin};const{error}=await supabase.storage.from('live-group-assets').upload(newPath,file,{contentType:file.type,upsert:false});if(error){logSupabaseError('upload-cover',error,context);throw new Error('No pudimos subir la portada. Revisa el diagnóstico del servidor.')}values.image_path=newPath}const{data:updated,error}=await supabase.from('live_groups').update(values).eq('id',id).select('image_path').single<{image_path:string|null}>();if(error||!updated){logSupabaseError('update-group',error,{groupId:id,newPath});if(newPath)await supabase.storage.from('live-group-assets').remove([newPath]);throw new Error('No pudimos actualizar el grupo.')}if(newPath&&updated.image_path!==newPath){logSupabaseError('verify-cover-path',null,{groupId:id,expectedPath:newPath,persistedPath:updated.image_path});await supabase.storage.from('live-group-assets').remove([newPath]);throw new Error('No pudimos confirmar la portada guardada.')}if(process.env.NODE_ENV!=='production'&&newPath)console.info('[upload-cover-saved]',{groupId:id,path:updated.image_path});if(newPath&&current?.image_path&&current.image_path!==newPath){const{error:removeError}=await supabase.storage.from('live-group-assets').remove([current.image_path]);if(removeError)logSupabaseError('remove-old-cover',removeError)}refresh(id)}
export async function addMember(data:FormData){await requireAdmin();const supabase=await createClient(),groupId=field(data,'group_id'),studentId=field(data,'student_id');const{error}=await supabase.from('live_group_members').insert({group_id:groupId,student_id:studentId});if(error?.code==='23505')return;if(error)throw new Error('El estudiante debe tener una matrícula activa en el curso base.');refresh(groupId)}
export async function removeMember(data:FormData){await requireAdmin();const supabase=await createClient(),groupId=field(data,'group_id');await supabase.from('live_group_members').delete().eq('group_id',groupId).eq('student_id',field(data,'student_id'));refresh(groupId)}
export async function createSection(data:FormData){await requireAdmin();const supabase=await createClient(),groupId=field(data,'group_id'),{data:last}=await supabase.from('live_group_sections').select('display_order').eq('group_id',groupId).order('display_order',{ascending:false}).limit(1).maybeSingle<{display_order:number}>();const{error}=await supabase.from('live_group_sections').insert({group_id:groupId,title:field(data,'title'),display_order:(last?.display_order??0)+1});if(error)throw new Error('No pudimos crear la sección.');refresh(groupId)}
export async function updateSection(data:FormData){await requireAdmin();const supabase=await createClient(),groupId=field(data,'group_id');await supabase.from('live_group_sections').update({title:field(data,'title'),status:field(data,'status')}).eq('id',field(data,'section_id'));refresh(groupId)}
export async function createItem(data:FormData){await requireAdmin();const supabase=await createClient(),groupId=field(data,'group_id'),sectionId=field(data,'section_id'),type=field(data,'item_type');if(!['text','file','link','assignment'].includes(type))throw new Error('Tipo de contenido inválido.');const{data:last}=await supabase.from('live_group_items').select('display_order').eq('section_id',sectionId).order('display_order',{ascending:false}).limit(1).maybeSingle<{display_order:number}>(),order=(last?.display_order??0)+1,title=field(data,'title')||null;if(type==='assignment'){if(!title)throw new Error('La entrega necesita un título.');const due=costaRicaDeadline(field(data,'due_date'),field(data,'due_time')),maxFiles=Number(field(data,'max_files')),maxBytes=Number(field(data,'max_file_mb'))*1024*1024;if(!due||maxFiles<1||maxFiles>20||maxBytes<1||maxBytes>50*1024*1024)throw new Error('Configuración de entrega inválida.');const{error}=await supabase.rpc('create_live_group_assignment',{p_section:sectionId,p_title:title,p_content:field(data,'content'),p_due_at:due,p_max_files:maxFiles,p_max_file_size_bytes:maxBytes});if(error){logSupabaseError('create-assignment',error);throw new Error('No pudimos crear la entrega.')}}else if(type==='file'){const file=data.get('file')as File|null;if(!file||!file.size||file.size>50*1024*1024||!isSafeAcademicFilename(file.name,file.type))throw new Error('Archivo inválido o peligroso.');const path=`${groupId}/materials/${randomUUID()}`;const{error:uploadError}=await supabase.storage.from('live-group-assets').upload(path,file,{contentType:file.type||'application/octet-stream',upsert:false});if(uploadError){logSupabaseError('upload-material',uploadError);throw new Error('No pudimos subir el material. Revisa que la migración correctiva de Storage esté aplicada.')}const{error}=await supabase.from('live_group_items').insert({section_id:sectionId,item_type:type,title,content:field(data,'content')||null,storage_path:path,original_filename:file.name,display_order:order});if(error){logSupabaseError('register-material',error);await supabase.storage.from('live-group-assets').remove([path]);throw new Error('No pudimos registrar el material.')}}else{if(type==='text'&&!field(data,'content'))throw new Error('El texto necesita contenido.');const values={section_id:sectionId,item_type:type,title,content:type==='text'?field(data,'content'):field(data,'description')||null,url:type==='link'?field(data,'url'):null,display_order:order};if(type==='link'){try{const url=new URL(values.url!);if(!['http:','https:'].includes(url.protocol))throw 0}catch{throw new Error('URL inválida.')}}const{error}=await supabase.from('live_group_items').insert(values);if(error){logSupabaseError('create-content',error);throw new Error('No pudimos crear el contenido.')}}refresh(groupId)}
export async function archiveItem(data:FormData){await requireAdmin();const supabase=await createClient(),groupId=field(data,'group_id');await supabase.from('live_group_items').update({status:'archived'}).eq('id',field(data,'item_id'));refresh(groupId)}

export async function updateItem(data:FormData){
  await requireAdmin()
  const supabase=await createClient(),groupId=field(data,'group_id'),itemId=field(data,'item_id')
  const{data:item}=await supabase.from('live_group_items').select('item_type,storage_path,activity_id').eq('id',itemId).single<{item_type:string;storage_path:string|null;activity_id:string|null}>()
  if(!item)throw new Error('Contenido no disponible.')
  const title=field(data,'title')||null,content=field(data,'content')||null
  if(item.item_type==='link'){
    const url=field(data,'url');try{const parsed=new URL(url);if(!['http:','https:'].includes(parsed.protocol))throw 0}catch{throw new Error('URL inválida.')}
    const{error}=await supabase.from('live_group_items').update({title,content,url}).eq('id',itemId);if(error)throw new Error('No pudimos actualizar el enlace.')
  }else if(item.item_type==='file'){
    const file=data.get('file')as File|null
    if(file?.size){if(file.size>50*1024*1024||!isSafeAcademicFilename(file.name,file.type))throw new Error('Archivo inválido o peligroso.');const path=`${groupId}/materials/${randomUUID()}`;const{error:uploadError}=await supabase.storage.from('live-group-assets').upload(path,file,{contentType:file.type||'application/octet-stream',upsert:false});if(uploadError)throw new Error('No pudimos subir el material.');const{error}=await supabase.from('live_group_items').update({title,content,storage_path:path,original_filename:file.name}).eq('id',itemId);if(error){await supabase.storage.from('live-group-assets').remove([path]);throw new Error('No pudimos registrar el material.')}if(item.storage_path)await supabase.storage.from('live-group-assets').remove([item.storage_path])}else{const{error}=await supabase.from('live_group_items').update({title,content}).eq('id',itemId);if(error)throw new Error('No pudimos actualizar el material.')}
  }else if(item.item_type==='assignment'){
    if(!title)throw new Error('La entrega necesita un título.');const due=costaRicaDeadline(field(data,'due_date'),field(data,'due_time')),maxFiles=Number(field(data,'max_files')),maxBytes=Number(field(data,'max_file_mb'))*1024*1024;if(!due||maxFiles<1||maxFiles>20||maxBytes<1||maxBytes>50*1024*1024)throw new Error('Configuración de entrega inválida.');const{error}=await supabase.from('live_group_items').update({title,content,due_at:due,max_files:maxFiles,max_file_size_bytes:maxBytes}).eq('id',itemId);if(error)throw new Error('No pudimos actualizar la entrega.');if(item.activity_id){const{error:activityError}=await supabase.from('activities').update({title,due_at:due,max_files:maxFiles,max_file_size_bytes:maxBytes,max_total_size_bytes:maxFiles*maxBytes}).eq('id',item.activity_id);if(activityError)throw new Error('No pudimos sincronizar la actividad.')}
  }else{if(!content)throw new Error('El texto necesita contenido.');const{error}=await supabase.from('live_group_items').update({title,content}).eq('id',itemId);if(error)throw new Error('No pudimos actualizar el texto.')}
  refresh(groupId)
}
export async function moveSection(data:FormData){await requireAdmin();const supabase=await createClient(),groupId=field(data,'group_id');await supabase.rpc('move_live_group_section',{p_id:field(data,'section_id'),p_direction:Number(field(data,'direction'))});refresh(groupId)}
export async function moveItem(data:FormData){await requireAdmin();const supabase=await createClient(),groupId=field(data,'group_id');await supabase.rpc('move_live_group_item',{p_id:field(data,'item_id'),p_direction:Number(field(data,'direction'))});refresh(groupId)}
export async function createAnnouncement(data:FormData){const{user}=await requireAdmin(),supabase=await createClient(),groupId=field(data,'group_id');const{error}=await supabase.from('live_group_announcements').insert({group_id:groupId,title:field(data,'title')||null,message:field(data,'message'),created_by:user.id});if(error)throw new Error('No pudimos publicar el anuncio.');refresh(groupId)}
