import Link from 'next/link'
import Image from 'next/image'
import { Eye } from 'lucide-react'
import { notFound } from 'next/navigation'
import { AccountShell } from '@/components/account/account-shell'
import { ConfirmSubmitButton } from '@/components/academic/confirm-submit-button'
import { LiveGroupAdminItemCard, type AdminLiveGroupItem } from '@/components/academic/live-group-admin-item-card'
import { LiveGroupItemForm } from '@/components/academic/live-group-item-form'
import { LiveGroupCoverInput, LiveGroupPublicFields } from '@/components/admin/live-group-public-fields'
import { LiveGroupArchiveAction } from '@/components/admin/live-group-archive-action'
import { requireAdmin } from '@/lib/auth/session'
import { createClient } from '@/lib/supabase/server'
import { resolveLiveGroupCover } from '@/lib/live-groups'
import { addMember, createAnnouncement, createSection, moveSection, removeMember, updateGroup, updateSection } from '../actions'

type Member={student_id:string;profiles:{full_name:string}|null}
type Section={id:string;title:string;status:string;display_order:number;live_group_items:AdminLiveGroupItem[]}

export default async function GroupAdminPage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{q?:string;error?:string}>}){
  await requireAdmin()
  const {id}=await params,{q='',error:formError}=await searchParams,supabase=await createClient()
  const {data:group}=await supabase.from('live_groups').select('id,name,status,starts_on,image_path,course_id,access_type,show_banner,show_catalog,public_summary,archived_at,courses(title)').eq('id',id).maybeSingle()
  if(!group)notFound()
  const candidateQuery=q.length<2?Promise.resolve({data:[]}):group.course_id
    ?supabase.from('enrollments').select('student_id,profiles!enrollments_student_id_fkey!inner(full_name)').eq('course_id',group.course_id).eq('status','active').ilike('profiles.full_name',`%${q}%`).limit(20)
    :supabase.from('profiles').select('id,full_name').eq('role','student').ilike('full_name',`%${q}%`).limit(20)
  const [{data:members},{data:sections},{data:announcements},{data:candidateRows}]=await Promise.all([
    supabase.from('live_group_members').select('student_id,profiles(full_name)').eq('group_id',id).order('joined_at'),
    supabase.from('live_group_sections').select('id,title,status,display_order,live_group_items(id,item_type,title,content,url,original_filename,due_at,status,activity_id,display_order,max_files,max_file_size_bytes)').eq('group_id',id).order('display_order').order('display_order',{referencedTable:'live_group_items'}),
    supabase.from('live_group_announcements').select('id,title,message,published_at').eq('group_id',id).order('published_at',{ascending:false}),
    candidateQuery,
  ])
  const candidates=(candidateRows??[]).map(candidate=>'student_id'in candidate?candidate:{student_id:candidate.id,profiles:{full_name:candidate.full_name}})
  const memberIds=new Set((members??[]).map(member=>member.student_id))
  const available=(candidates??[]).filter(candidate=>!memberIds.has(candidate.student_id))
  const course=Array.isArray(group.courses)?group.courses[0]:group.courses
  const coverUrl=await resolveLiveGroupCover(supabase,group.image_path)
  return <AccountShell title={group.name} eyebrow={course?.title?`Grupo en vivo · ${course.title}`:'Grupo público en vivo'}>
    {formError&&<p role="alert" className="mb-5 rounded-xl border border-destructive/30 bg-destructive/5 p-4 text-sm text-destructive">{formError}</p>}
    <div className="mb-6 flex flex-wrap justify-end gap-3"><Link href={`/admin/grupos/${id}/preview`} target="_blank" className="inline-flex items-center gap-2 rounded-xl border border-primary px-4 py-2 text-sm font-bold text-primary"><Eye className="h-4 w-4"/>Vista previa como estudiante</Link><LiveGroupArchiveAction groupId={id} archived={!!group.archived_at}/></div>
    <div className="space-y-8">
      <section className="rounded-2xl border border-border bg-background p-6"><h2 className="text-xl font-bold">Configuración</h2>{coverUrl&&<div className="mt-4"><p className="mb-2 text-sm font-bold">Portada actual</p><div className="relative aspect-[3/1] max-w-xl overflow-hidden rounded-xl border bg-secondary"><Image src={coverUrl} alt={`Portada actual de ${group.name}`} fill sizes="576px" className="object-cover"/></div></div>}<form action={updateGroup} className="mt-4 grid gap-4 sm:grid-cols-2"><input type="hidden" name="group_id" value={id}/><label className="text-sm font-bold">Nombre<input name="name" defaultValue={group.name} required className="mt-2 h-11 w-full rounded-xl border bg-background px-3"/></label><label className="text-sm font-bold">Estado<select name="status" defaultValue={group.status} className="mt-2 h-11 w-full rounded-xl border bg-background px-3"><option value="preparation">Preparación</option><option value="active">Activo</option><option value="finished">Finalizado</option></select></label><label className="text-sm font-bold">Inicio<input type="date" name="starts_on" defaultValue={group.starts_on??''} className="mt-2 h-11 w-full rounded-xl border bg-background px-3"/></label><LiveGroupCoverInput label={coverUrl?'Cambiar portada':'Portada'}/><LiveGroupPublicFields accessType={group.access_type} showBanner={group.show_banner} showCatalog={group.show_catalog} summary={group.public_summary??''} allowPrivate={!!group.course_id}/><button className="h-11 rounded-xl bg-primary font-bold text-primary-foreground sm:col-span-2">Guardar cambios</button></form></section>
      <section className="rounded-2xl border border-border bg-background p-6"><h2 className="text-xl font-bold">Participantes</h2><form className="mt-4 flex flex-col gap-2 sm:flex-row"><input name="q" defaultValue={q} placeholder="Buscar estudiante por nombre" className="h-11 flex-1 rounded-xl border px-3"/><button className="rounded-xl border px-4 py-2 font-bold">Buscar</button></form>{q.length>=2&&<div className="mt-3 space-y-2">{available.map(candidate=><form key={candidate.student_id} action={addMember} className="flex items-center justify-between gap-3 rounded-xl bg-secondary p-3"><input type="hidden" name="group_id" value={id}/><input type="hidden" name="student_id" value={candidate.student_id}/><span className="break-words">{(Array.isArray(candidate.profiles)?candidate.profiles[0]:candidate.profiles)?.full_name}</span><button className="font-bold text-primary">Añadir</button></form>)}{available.length===0&&<p className="rounded-xl border border-dashed p-4 text-sm text-muted-foreground">No encontramos estudiantes con esa búsqueda.</p>}</div>}<div className="mt-5 divide-y">{((members??[]) as unknown as Member[]).map(member=><div key={member.student_id} className="flex items-center justify-between gap-3 py-3"><span className="break-words">{member.profiles?.full_name}</span><form action={removeMember}><input type="hidden" name="group_id" value={id}/><input type="hidden" name="student_id" value={member.student_id}/><ConfirmSubmitButton label="Quitar" title="Quitar participante" message="Perderá el acceso al grupo y a sus materiales. Su historial académico se conservará." className="text-sm font-bold text-destructive"/></form></div>)}</div></section>
      <section><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><h2 className="text-2xl font-extrabold">Contenido</h2><form action={createSection} className="flex gap-2"><input type="hidden" name="group_id" value={id}/><input name="title" required placeholder="Nueva sección" className="h-10 min-w-0 flex-1 rounded-xl border px-3"/><button className="rounded-xl bg-primary px-4 font-bold text-primary-foreground">Crear</button></form></div><div className="mt-5 space-y-5">{((sections??[]) as unknown as Section[]).map(section=><article key={section.id} className="rounded-2xl border border-border bg-background p-4 sm:p-5"><form action={updateSection} className="flex flex-col gap-2 sm:flex-row"><input type="hidden" name="group_id" value={id}/><input type="hidden" name="section_id" value={section.id}/><input name="title" defaultValue={section.title} required className="h-10 min-w-0 flex-1 rounded-xl border px-3 font-bold"/><select name="status" defaultValue={section.status} className="h-10 rounded-xl border px-3"><option value="draft">Borrador</option><option value="published">Publicado</option><option value="archived">Archivado</option></select><button className="h-10 rounded-xl border px-3 font-bold">Guardar</button></form><form action={moveSection} className="mt-2 flex gap-3"><input type="hidden" name="group_id" value={id}/><input type="hidden" name="section_id" value={section.id}/><button name="direction" value="-1" className="text-xs font-bold text-primary">Subir</button><button name="direction" value="1" className="text-xs font-bold text-primary">Bajar</button></form><div className="mt-4 space-y-3">{section.live_group_items.map(item=><LiveGroupAdminItemCard key={item.id} groupId={id} item={item}/>)}</div><LiveGroupItemForm groupId={id} sectionId={section.id}/></article>)}</div></section>
      <section className="rounded-2xl border border-border bg-background p-6"><h2 className="text-xl font-bold">Anuncios</h2><form action={createAnnouncement} className="mt-4 grid gap-3"><input type="hidden" name="group_id" value={id}/><input name="title" placeholder="Título opcional" className="h-10 rounded-xl border px-3"/><textarea name="message" required placeholder="Mensaje" className="min-h-24 rounded-xl border p-3"/><button className="rounded-xl bg-primary px-4 py-2 font-bold text-primary-foreground">Publicar anuncio</button></form><div className="mt-4 space-y-3">{announcements?.map(item=><article key={item.id} className="rounded-xl bg-secondary p-4"><strong>{item.title??'Aviso'}</strong><p className="mt-1 whitespace-pre-wrap text-sm">{item.message}</p></article>)}</div></section>
    </div>
  </AccountShell>
}
